In [1]:
import argparse
import csv
import torch
import numpy as np
from tqdm import tqdm
import scanpy as sc
from torch.utils.data import DataLoader
from model.dataset import BagsDataset, custom_collate_fn
from model.model import MIL

In [2]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [3]:
def load_all_genes(reference_gene_file):
    all_genes = []
    with open(reference_gene_file, 'r') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            all_genes.append(row['Gene'])
    return all_genes

all_genes = load_all_genes('data/human.csv')

In [4]:
model_path = '10_old_data/all/final_model.pth'

In [5]:
model = MIL(all_genes).to(device)
model.load_state_dict(torch.load(model_path, map_location=device))

In [9]:
model.get

<bound method Module.get_parameter of MIL(
  (distance): Distance(
    (sparsemax): Sparsemax()
  )
  (gene_expression): Gene_expression(
    (softmax): Softmax(dim=-1)
  )
  (immunogenicity): Immunogenicity()
)>

In [10]:
adata = sc.read('data.h5ad')

In [11]:
adata.obs

                   leiden     X      Y    T cell_type    T_pred
AAACAAGTATCTCCCA-1      7  5000  10200  0.0         0       NaN
AAACAATCTACTAGCA-1      8   300   4300  3.0         1  0.837607
AAACACCAATAACTGC-1      4  5900   1900  0.0         0       NaN
AAACAGAGCGACTCCT-1      2  1400   9400  1.0         0       NaN
AAACAGCTTTCAGAAG-1      6  4300    900  3.0         1  0.854544
...                   ...   ...    ...  ...       ...       ...
TTGTTCAGTGTGCTAC-1     11  2400   6400  0.0         1  0.843169
TTGTTTCACATCCAGG-1      4  5800   4200  0.0         0       NaN
TTGTTTCATTAGTCTA-1      4  6000   3000  2.0         0       NaN
TTGTTTCCATACAACT-1      4  4500   2700  0.0         0       NaN
TTGTTTGTGTAAATTC-1      6   700   5100  2.0         1  0.839343

[3460 rows x 6 columns]

In [14]:
check = sc.read('check.h5ad')

In [15]:
check.obs

                   leiden     X      Y  T cell_type
AAACAAGTATCTCCCA-1      7  5000  10200  0         0
AAACAATCTACTAGCA-1      8   300   4300  1         1
AAACACCAATAACTGC-1      4  5900   1900  0         0
AAACAGAGCGACTCCT-1      2  1400   9400  1         0
AAACAGCTTTCAGAAG-1      6  4300    900  1         1
...                   ...   ...    ... ..       ...
TTGTTCAGTGTGCTAC-1     11  2400   6400  0         1
TTGTTTCACATCCAGG-1      4  5800   4200  0         0
TTGTTTCATTAGTCTA-1      4  6000   3000  1         0
TTGTTTCCATACAACT-1      4  4500   2700  0         0
TTGTTTGTGTAAATTC-1      6   700   5100  1         1

[3460 rows x 5 columns]