In [1]:
import pandas as pd
import numpy as np
import scanpy as sc
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset
from scipy.spatial.distance import cdist
import torch.nn.functional as F

In [4]:
adata = sc.read_h5ad('../example.h5ad')

In [5]:
adata.obs['X'] = adata.obs['array_row'] *100
adata.obs['Y'] = adata.obs['array_col'] *100
adata.obs

                    in_tissue  array_row  array_col  n_counts     X      Y
AAACAAGTATCTCCCA-1          1         50        102    5625.0  5000  10200
AAACACCAATAACTGC-1          1         59         19    9159.0  5900   1900
AAACAGAGCGACTCCT-1          1         14         94    2660.0  1400   9400
AAACAGGGTCTATATT-1          1         47         13    9020.0  4700   1300
AAACAGTGTTCCTGGG-1          1         73         43    9714.0  7300   4300
...                       ...        ...        ...       ...   ...    ...
TTGTTGTGTGTCAAGA-1          1         31         77    7260.0  3100   7700
TTGTTTCACATCCAGG-1          1         58         42    7510.0  5800   4200
TTGTTTCATTAGTCTA-1          1         60         30    5742.0  6000   3000
TTGTTTCCATACAACT-1          1         45         27   20118.0  4500   2700
TTGTTTGTATTACACG-1          1         73         41    8169.0  7300   4100

[2640 rows x 6 columns]

In [6]:
adata.obs['tcr'] = np.random.randint(2, size=adata.n_obs)

In [7]:
adata.obs

,in_tissue,array_row,array_col,n_counts,X,Y,tcr
AAACAAGTATCTCCCA-1,1,50,102,5625.0,5000,10200,1
AAACACCAATAACTGC-1,1,59,19,9159.0,5900,1900,0
AAACAGAGCGACTCCT-1,1,14,94,2660.0,1400,9400,1
AAACAGGGTCTATATT-1,1,47,13,9020.0,4700,1300,1
AAACAGTGTTCCTGGG-1,1,73,43,9714.0,7300,4300,0
...,...,...,...,...,...,...,...
TTGTTGTGTGTCAAGA-1,1,31,77,7260.0,3100,7700,1
TTGTTTCACATCCAGG-1,1,58,42,7510.0,5800,4200,1
TTGTTTCATTAGTCTA-1,1,60,30,5742.0,6000,3000,1
TTGTTTCCATACAACT-1,1,45,27,20118.0,4500,2700,0
TTGTTTGTATTACACG-1,1,73,41,8169.0,7300,4100,0

In [8]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

cpu

In [9]:
class BagsDataset(Dataset):
    def __init__(self, adata, radius=50):
        self.bags = self.create_bags(adata, radius)

    def __len__(self):
        return len(self.bags)

    def __getitem__(self, idx):
        bag = self.bags[idx]
        instances = bag['instances']
        label = bag['label']
        return instances, label

    def create_bags(self, adata, radius):
        spatial_coords_x = adata.obs['X']
        spatial_coords_y = adata.obs['Y']
        spatial_coords = np.array(list(zip(spatial_coords_x, spatial_coords_y)))

        gene_expression = adata.X
        labels = adata.obs['tcr'].values
        bags = {}

        dist_matrix = cdist(spatial_coords, spatial_coords, metric='euclidean')

        for i in range(len(spatial_coords)):
            in_circle = np.where(dist_matrix[i] <= radius)[0]

            bag_data = gene_expression[in_circle].todense()  # Convert sparse matrix to dense
            bag_label = labels[i]

            bags[i] = {
                'instances': bag_data,
                'label': bag_label
            }
            print(f"Bag {i} contains {len(in_circle)} instances")

        return bags

In [10]:
dataset = BagsDataset(adata, radius=200)
dataset.__getitem__(0)

Bag 0 contains 9 instances
Bag 1 contains 9 instances
Bag 2 contains 9 instances
Bag 3 contains 7 instances
Bag 4 contains 5 instances
Bag 5 contains 9 instances
Bag 6 contains 5 instances
Bag 7 contains 9 instances
Bag 8 contains 8 instances
Bag 9 contains 9 instances
Bag 10 contains 9 instances
Bag 11 contains 9 instances
Bag 12 contains 4 instances
Bag 13 contains 9 instances
Bag 14 contains 9 instances
Bag 15 contains 8 instances
Bag 16 contains 8 instances
Bag 17 contains 9 instances
Bag 18 contains 9 instances
Bag 19 contains 9 instances
Bag 20 contains 9 instances
Bag 21 contains 8 instances
Bag 22 contains 8 instances
Bag 23 contains 9 instances
Bag 24 contains 9 instances
Bag 25 contains 9 instances
Bag 26 contains 9 instances
Bag 27 contains 9 instances
Bag 28 contains 9 instances
Bag 29 contains 9 instances
Bag 30 contains 9 instances
Bag 31 contains 9 instances
Bag 32 contains 9 instances
Bag 33 contains 9 instances
Bag 34 contains 9 instances
Bag 35 contains 9 instances
Bag 36 contains 9 instances
Bag 37 contains 9 instances
Bag 38 contains 9 instances
Bag 39 contains 9 instances
Bag 40 contains 9 instances
Bag 41 contains 6 instances
Bag 42 contains 9 instances
Bag 43 contains 9 instances
Bag 44 contains 9 instances
Bag 45 contains 7 instances
Bag 46 contains 9 instances
Bag 47 contains 9 instances
Bag 48 contains 9 instances
Bag 49 contains 9 instances
Bag 50 contains 9 instances
Bag 51 contains 9 instances
Bag 52 contains 9 instances
Bag 53 contains 9 instances
Bag 54 contains 9 instances
Bag 55 contains 9 instances
Bag 56 contains 9 instances
Bag 57 contains 9 instances
Bag 58 contains 9 instances
Bag 59 contains 9 instances
Bag 60 contains 9 instances
Bag 61 contains 9 instances
Bag 62 contains 9 instances
Bag 63 contains 9 instances
Bag 64 contains 9 instances
Bag 65 contains 9 instances
Bag 66 contains 9 instances
Bag 67 contains 9 instances
Bag 68 contains 9 instances
Bag 69 contains 9 instances
Bag 70 contains 9 instances
Bag 71 contains 9 instances
Bag 72 contains 5 instances
Bag 73 contains 8 instances
Bag 74 contains 9 instances
Bag 75 contains 9 instances
Bag 76 contains 9 instances
Bag 77 contains 9 instances
Bag 78 contains 9 instances
Bag 79 contains 9 instances
Bag 80 contains 8 instances
Bag 81 contains 9 instances
Bag 82 contains 6 instances
Bag 83 contains 5 instances
Bag 84 contains 9 instances
Bag 85 contains 5 instances
Bag 86 contains 9 instances
Bag 87 contains 9 instances
Bag 88 contains 8 instances
Bag 89 contains 9 instances
Bag 90 contains 9 instances
Bag 91 contains 9 instances
Bag 92 contains 9 instances
Bag 93 contains 9 instances
Bag 94 contains 9 instances
Bag 95 contains 6 instances
Bag 96 contains 9 instances
Bag 97 contains 7 instances
Bag 98 contains 9 instances
Bag 99 contains 9 instances
Bag 100 contains 9 instances
Bag 101 contains 9 instances
Bag 102 contains 9 instances
Bag 103 contains 9 instances
Bag 104 contains 9 instances
Bag 105 contains 9 instances
Bag 106 contains 9 instances
Bag 107 contains 9 instances
Bag 108 contains 9 instances
Bag 109 contains 9 instances
Bag 110 contains 8 instances
Bag 111 contains 9 instances
Bag 112 contains 9 instances
Bag 113 contains 9 instances
Bag 114 contains 9 instances
Bag 115 contains 9 instances
Bag 116 contains 9 instances
Bag 117 contains 9 instances
Bag 118 contains 9 instances
Bag 119 contains 9 instances
Bag 120 contains 9 instances
Bag 121 contains 9 instances
Bag 122 contains 9 instances
Bag 123 contains 9 instances
Bag 124 contains 9 instances
Bag 125 contains 9 instances
Bag 126 contains 9 instances
Bag 127 contains 9 instances
Bag 128 contains 9 instances
Bag 129 contains 9 instances
Bag 130 contains 9 instances
Bag 131 contains 9 instances
Bag 132 contains 9 instances
Bag 133 contains 8 instances
Bag 134 contains 9 instances
Bag 135 contains 9 instances
Bag 136 contains 9 instances
Bag 137 contains 9 instances
Bag 138 contains 9 instances
Bag 139 contains 9 instances
Bag 140 contains 9 instances
Bag 141 contains 9 instances
Bag 142 contains 9 instances
Bag 143 contains 9 instances
Bag 144 contains 8 instances
Bag 145 contains 9 instances
Bag 146 contains 9 instances
Bag 147 contains 9 instances
Bag 148 contains 8 instances
Bag 149 contains 9 instances
Bag 150 contains 9 instances
Bag 151 contains 9 instances
Bag 152 contains 9 instances
Bag 153 contains 9 instances
Bag 154 contains 9 instances
Bag 155 contains 9 instances
Bag 156 contains 9 instances
Bag 157 contains 9 instances
Bag 158 contains 8 instances
Bag 159 contains 9 instances
Bag 160 contains 9 instances
Bag 161 contains 9 instances
Bag 162 contains 9 instances
Bag 163 contains 9 instances
Bag 164 contains 7 instances
Bag 165 contains 9 instances
Bag 166 contains 9 instances
Bag 167 contains 9 instances
Bag 168 contains 9 instances
Bag 169 contains 9 instances
Bag 170 contains 8 instances
Bag 171 contains 9 instances
Bag 172 contains 9 instances
Bag 173 contains 9 instances
Bag 174 contains 9 instances
Bag 175 contains 6 instances
Bag 176 contains 9 instances
Bag 177 contains 9 instances
Bag 178 contains 9 instances
Bag 179 contains 9 instances
Bag 180 contains 9 instances
Bag 181 contains 9 instances
Bag 182 contains 3 instances
Bag 183 contains 9 instances
Bag 184 contains 8 instances
Bag 185 contains 9 instances
Bag 186 contains 9 instances
Bag 187 contains 9 instances
Bag 188 contains 9 instances
Bag 189 contains 5 instances
Bag 190 contains 9 instances
Bag 191 contains 8 instances
Bag 192 contains 9 instances
Bag 193 contains 9 instances
Bag 194 contains 9 instances
Bag 195 contains 9 instances
Bag 196 contains 9 instances
Bag 197 contains 9 instances
Bag 198 contains 9 instances
Bag 199 contains 9 instances
Bag 200 contains 9 instances
Bag 201 contains 9 instances
Bag 202 contains 9 instances
Bag 203 contains 9 instances
Bag 204 contains 9 instances
Bag 205 contains 6 instances
Bag 206 contains 9 instances
Bag 207 contains 9 instances
Bag 208 contains 9 instances
Bag 209 contains 9 instances
Bag 210 contains 9 instances
Bag 211 contains 9 instances
Bag 212 contains 9 instances
Bag 213 contains 9 instances
Bag 214 contains 9 instances
Bag 215 contains 9 instances
Bag 216 contains 9 instances
Bag 217 contains 9 instances
Bag 218 contains 9 instances
Bag 219 contains 8 instances
Bag 220 contains 9 instances
Bag 221 contains 9 instances
Bag 222 contains 9 instances
Bag 223 contains 9 instances
Bag 224 contains 9 instances
Bag 225 contains 5 instances
Bag 226 contains 9 instances
Bag 227 contains 9 instances
Bag 228 contains 8 instances
Bag 229 contains 9 instances
Bag 230 contains 9 instances
Bag 231 contains 9 instances
Bag 232 contains 9 instances
Bag 233 contains 9 instances
Bag 234 contains 9 instances
Bag 235 contains 9 instances
Bag 236 contains 9 instances
Bag 237 contains 9 instances
Bag 238 contains 9 instances
Bag 239 contains 8 instances
Bag 240 contains 9 instances
Bag 241 contains 9 instances
Bag 242 contains 6 instances
Bag 243 contains 9 instances
Bag 244 contains 8 instances
Bag 245 contains 9 instances
Bag 246 contains 9 instances
Bag 247 contains 9 instances
Bag 248 contains 9 instances
Bag 249 contains 9 instances
Bag 250 contains 9 instances
Bag 251 contains 9 instances
Bag 252 contains 5 instances
Bag 253 contains 9 instances
Bag 254 contains 7 instances
Bag 255 contains 6 instances
Bag 256 contains 9 instances
Bag 257 contains 9 instances
Bag 258 contains 8 instances
Bag 259 contains 9 instances
Bag 260 contains 9 instances
Bag 261 contains 9 instances
Bag 262 contains 9 instances
Bag 263 contains 9 instances
Bag 264 contains 9 instances
Bag 265 contains 9 instances
Bag 266 contains 9 instances
Bag 267 contains 9 instances
Bag 268 contains 9 instances
Bag 269 contains 5 instances
Bag 270 contains 8 instances
Bag 271 contains 8 instances
Bag 272 contains 9 instances
Bag 273 contains 9 instances
Bag 274 contains 9 instances
Bag 275 contains 9 instances
Bag 276 contains 6 instances
Bag 277 contains 8 instances
Bag 278 contains 9 instances
Bag 279 contains 9 instances
Bag 280 contains 6 instances
Bag 281 contains 8 instances
Bag 282 contains 9 instances
Bag 283 contains 9 instances
Bag 284 contains 9 instances
Bag 285 contains 9 instances
Bag 286 contains 9 instances
Bag 287 contains 9 instances
Bag 288 contains 9 instances
Bag 289 contains 9 instances
Bag 290 contains 9 instances
Bag 291 contains 5 instances
Bag 292 contains 9 instances
Bag 293 contains 9 instances
Bag 294 contains 9 instances
Bag 295 contains 9 instances
Bag 296 contains 9 instances
Bag 297 contains 9 instances
Bag 298 contains 9 instances
Bag 299 contains 9 instances
Bag 300 contains 9 instances
Bag 301 contains 9 instances
Bag 302 contains 9 instances
Bag 303 contains 9 instances
Bag 304 contains 9 instances
Bag 305 contains 9 instances
Bag 306 contains 9 instances
Bag 307 contains 9 instances
Bag 308 contains 6 instances
Bag 309 contains 9 instances
Bag 310 contains 5 instances
Bag 311 contains 9 instances
Bag 312 contains 9 instances
Bag 313 contains 9 instances
Bag 314 contains 9 instances
Bag 315 contains 9 instances
Bag 316 contains 9 instances
Bag 317 contains 9 instances
Bag 318 contains 9 instances
Bag 319 contains 9 instances
Bag 320 contains 9 instances
Bag 321 contains 9 instances
Bag 322 contains 9 instances
Bag 323 contains 5 instances
Bag 324 contains 9 instances
Bag 325 contains 9 instances
Bag 326 contains 9 instances
Bag 327 contains 8 instances
Bag 328 contains 9 instances
Bag 329 contains 9 instances
Bag 330 contains 9 instances
Bag 331 contains 9 instances
Bag 332 contains 9 instances
Bag 333 contains 9 instances
Bag 334 contains 9 instances
Bag 335 contains 9 instances
Bag 336 contains 9 instances
Bag 337 contains 9 instances
Bag 338 contains 9 instances
Bag 339 contains 9 instances
Bag 340 contains 9 instances
Bag 341 contains 9 instances
Bag 342 contains 9 instances
Bag 343 contains 7 instances
Bag 344 contains 9 instances
Bag 345 contains 9 instances
Bag 346 contains 9 instances
Bag 347 contains 9 instances
Bag 348 contains 9 instances
Bag 349 contains 9 instances
Bag 350 contains 9 instances
Bag 351 contains 9 instances
Bag 352 contains 9 instances
Bag 353 contains 9 instances
Bag 354 contains 8 instances
Bag 355 contains 3 instances
Bag 356 contains 9 instances
Bag 357 contains 9 instances
Bag 358 contains 9 instances
Bag 359 contains 9 instances
Bag 360 contains 9 instances
Bag 361 contains 9 instances
Bag 362 contains 9 instances
Bag 363 contains 9 instances
Bag 364 contains 9 instances
Bag 365 contains 9 instances
Bag 366 contains 9 instances
Bag 367 contains 9 instances
Bag 368 contains 9 instances
Bag 369 contains 9 instances
Bag 370 contains 9 instances
Bag 371 contains 7 instances
Bag 372 contains 9 instances
Bag 373 contains 9 instances
Bag 374 contains 9 instances
Bag 375 contains 9 instances
Bag 376 contains 5 instances
Bag 377 contains 9 instances
Bag 378 contains 9 instances
Bag 379 contains 9 instances
Bag 380 contains 9 instances
Bag 381 contains 9 instances
Bag 382 contains 9 instances
Bag 383 contains 9 instances
Bag 384 contains 9 instances
Bag 385 contains 9 instances
Bag 386 contains 9 instances
Bag 387 contains 9 instances
Bag 388 contains 9 instances
Bag 389 contains 9 instances
Bag 390 contains 9 instances
Bag 391 contains 9 instances
Bag 392 contains 9 instances
Bag 393 contains 6 instances
Bag 394 contains 7 instances
Bag 395 contains 9 instances
Bag 396 contains 9 instances
Bag 397 contains 9 instances
Bag 398 contains 9 instances
Bag 399 contains 6 instances
Bag 400 contains 9 instances
Bag 401 contains 9 instances
Bag 402 contains 9 instances
Bag 403 contains 6 instances
Bag 404 contains 9 instances
Bag 405 contains 9 instances
Bag 406 contains 9 instances
Bag 407 contains 9 instances
Bag 408 contains 9 instances
Bag 409 contains 9 instances
Bag 410 contains 9 instances
Bag 411 contains 9 instances
Bag 412 contains 7 instances
Bag 413 contains 9 instances
Bag 414 contains 9 instances
Bag 415 contains 9 instances
Bag 416 contains 9 instances
Bag 417 contains 9 instances
Bag 418 contains 9 instances
Bag 419 contains 8 instances
Bag 420 contains 9 instances
Bag 421 contains 9 instances
Bag 422 contains 8 instances
Bag 423 contains 9 instances
Bag 424 contains 8 instances
Bag 425 contains 9 instances
Bag 426 contains 9 instances
Bag 427 contains 9 instances
Bag 428 contains 1 instances
Bag 429 contains 7 instances
Bag 430 contains 9 instances
Bag 431 contains 7 instances
Bag 432 contains 9 instances
Bag 433 contains 9 instances
Bag 434 contains 9 instances
Bag 435 contains 9 instances
Bag 436 contains 9 instances
Bag 437 contains 5 instances
Bag 438 contains 9 instances
Bag 439 contains 9 instances
Bag 440 contains 9 instances
Bag 441 contains 9 instances
Bag 442 contains 9 instances
Bag 443 contains 9 instances
Bag 444 contains 9 instances
Bag 445 contains 6 instances
Bag 446 contains 8 instances
Bag 447 contains 9 instances
Bag 448 contains 8 instances
Bag 449 contains 9 instances
Bag 450 contains 9 instances
Bag 451 contains 9 instances
Bag 452 contains 9 instances
Bag 453 contains 9 instances
Bag 454 contains 9 instances
Bag 455 contains 9 instances
Bag 456 contains 9 instances
Bag 457 contains 9 instances
Bag 458 contains 9 instances
Bag 459 contains 9 instances
Bag 460 contains 9 instances
Bag 461 contains 6 instances
Bag 462 contains 9 instances
Bag 463 contains 8 instances
Bag 464 contains 9 instances
Bag 465 contains 9 instances
Bag 466 contains 9 instances
Bag 467 contains 8 instances
Bag 468 contains 9 instances
Bag 469 contains 9 instances
Bag 470 contains 9 instances
Bag 471 contains 9 instances
Bag 472 contains 9 instances
Bag 473 contains 9 instances
Bag 474 contains 9 instances
Bag 475 contains 9 instances
Bag 476 contains 9 instances
Bag 477 contains 9 instances
Bag 478 contains 9 instances
Bag 479 contains 9 instances
Bag 480 contains 9 instances
Bag 481 contains 9 instances
Bag 482 contains 9 instances
Bag 483 contains 9 instances
Bag 484 contains 9 instances
Bag 485 contains 9 instances
Bag 486 contains 9 instances
Bag 487 contains 9 instances
Bag 488 contains 9 instances
Bag 489 contains 9 instances
Bag 490 contains 9 instances
Bag 491 contains 9 instances
Bag 492 contains 9 instances
Bag 493 contains 9 instances
Bag 494 contains 9 instances
Bag 495 contains 9 instances
Bag 496 contains 9 instances
Bag 497 contains 9 instances
Bag 498 contains 9 instances
Bag 499 contains 9 instances
Bag 500 contains 9 instances
Bag 501 contains 9 instances
Bag 502 contains 9 instances
Bag 503 contains 9 instances
Bag 504 contains 9 instances
Bag 505 contains 9 instances
Bag 506 contains 9 instances
Bag 507 contains 8 instances
Bag 508 contains 9 instances
Bag 509 contains 9 instances
Bag 510 contains 9 instances
Bag 511 contains 9 instances
Bag 512 contains 9 instances
Bag 513 contains 9 instances
Bag 514 contains 9 instances
Bag 515 contains 9 instances
Bag 516 contains 9 instances
Bag 517 contains 4 instances
Bag 518 contains 7 instances
Bag 519 contains 9 instances
Bag 520 contains 3 instances
Bag 521 contains 9 instances
Bag 522 contains 9 instances
Bag 523 contains 9 instances
Bag 524 contains 9 instances
Bag 525 contains 9 instances
Bag 526 contains 9 instances
Bag 527 contains 9 instances
Bag 528 contains 9 instances
Bag 529 contains 9 instances
Bag 530 contains 9 instances
Bag 531 contains 9 instances
Bag 532 contains 9 instances
Bag 533 contains 9 instances
Bag 534 contains 9 instances
Bag 535 contains 9 instances
Bag 536 contains 9 instances
Bag 537 contains 9 instances
Bag 538 contains 9 instances
Bag 539 contains 9 instances
Bag 540 contains 9 instances
Bag 541 contains 9 instances
Bag 542 contains 9 instances
Bag 543 contains 9 instances
Bag 544 contains 9 instances
Bag 545 contains 7 instances
Bag 546 contains 9 instances
Bag 547 contains 9 instances
Bag 548 contains 4 instances
Bag 549 contains 9 instances
Bag 550 contains 9 instances
Bag 551 contains 9 instances
Bag 552 contains 9 instances
Bag 553 contains 8 instances
Bag 554 contains 9 instances
Bag 555 contains 9 instances
Bag 556 contains 9 instances
Bag 557 contains 9 instances
Bag 558 contains 9 instances
Bag 559 contains 9 instances
Bag 560 contains 9 instances
Bag 561 contains 9 instances
Bag 562 contains 9 instances
Bag 563 contains 9 instances
Bag 564 contains 9 instances
Bag 565 contains 7 instances
Bag 566 contains 9 instances
Bag 567 contains 9 instances
Bag 568 contains 9 instances
Bag 569 contains 9 instances
Bag 570 contains 9 instances
Bag 571 contains 9 instances
Bag 572 contains 9 instances
Bag 573 contains 9 instances
Bag 574 contains 9 instances
Bag 575 contains 9 instances
Bag 576 contains 9 instances
Bag 577 contains 8 instances
Bag 578 contains 7 instances
Bag 579 contains 9 instances
Bag 580 contains 9 instances
Bag 581 contains 9 instances
Bag 582 contains 9 instances
Bag 583 contains 8 instances
Bag 584 contains 9 instances
Bag 585 contains 9 instances
Bag 586 contains 9 instances
Bag 587 contains 9 instances
Bag 588 contains 9 instances
Bag 589 contains 9 instances
Bag 590 contains 9 instances
Bag 591 contains 9 instances
Bag 592 contains 9 instances
Bag 593 contains 9 instances
Bag 594 contains 9 instances
Bag 595 contains 9 instances
Bag 596 contains 7 instances
Bag 597 contains 9 instances
Bag 598 contains 9 instances
Bag 599 contains 9 instances
Bag 600 contains 9 instances
Bag 601 contains 9 instances
Bag 602 contains 9 instances
Bag 603 contains 9 instances
Bag 604 contains 9 instances
Bag 605 contains 9 instances
Bag 606 contains 5 instances
Bag 607 contains 6 instances
Bag 608 contains 8 instances
Bag 609 contains 9 instances
Bag 610 contains 9 instances
Bag 611 contains 9 instances
Bag 612 contains 9 instances
Bag 613 contains 6 instances
Bag 614 contains 9 instances
Bag 615 contains 9 instances
Bag 616 contains 7 instances
Bag 617 contains 9 instances
Bag 618 contains 9 instances
Bag 619 contains 9 instances
Bag 620 contains 9 instances
Bag 621 contains 9 instances
Bag 622 contains 9 instances
Bag 623 contains 9 instances
Bag 624 contains 9 instances
Bag 625 contains 3 instances
Bag 626 contains 9 instances
Bag 627 contains 9 instances
Bag 628 contains 6 instances
Bag 629 contains 9 instances
Bag 630 contains 3 instances
Bag 631 contains 9 instances
Bag 632 contains 5 instances
Bag 633 contains 9 instances
Bag 634 contains 9 instances
Bag 635 contains 7 instances
Bag 636 contains 7 instances
Bag 637 contains 8 instances
Bag 638 contains 9 instances
Bag 639 contains 9 instances
Bag 640 contains 9 instances
Bag 641 contains 9 instances
Bag 642 contains 8 instances
Bag 643 contains 9 instances
Bag 644 contains 9 instances
Bag 645 contains 9 instances
Bag 646 contains 9 instances
Bag 647 contains 9 instances
Bag 648 contains 9 instances
Bag 649 contains 9 instances
Bag 650 contains 9 instances
Bag 651 contains 9 instances
Bag 652 contains 9 instances
Bag 653 contains 9 instances
Bag 654 contains 9 instances
Bag 655 contains 9 instances
Bag 656 contains 8 instances
Bag 657 contains 6 instances
Bag 658 contains 9 instances
Bag 659 contains 9 instances
Bag 660 contains 9 instances
Bag 661 contains 9 instances
Bag 662 contains 9 instances
Bag 663 contains 9 instances
Bag 664 contains 9 instances
Bag 665 contains 9 instances
Bag 666 contains 6 instances
Bag 667 contains 9 instances
Bag 668 contains 9 instances
Bag 669 contains 9 instances
Bag 670 contains 9 instances
Bag 671 contains 9 instances
Bag 672 contains 9 instances
Bag 673 contains 9 instances
Bag 674 contains 9 instances
Bag 675 contains 9 instances
Bag 676 contains 6 instances
Bag 677 contains 9 instances
Bag 678 contains 9 instances
Bag 679 contains 6 instances
Bag 680 contains 9 instances
Bag 681 contains 9 instances
Bag 682 contains 9 instances
Bag 683 contains 9 instances
Bag 684 contains 9 instances
Bag 685 contains 9 instances
Bag 686 contains 9 instances
Bag 687 contains 9 instances
Bag 688 contains 9 instances
Bag 689 contains 9 instances
Bag 690 contains 5 instances
Bag 691 contains 4 instances
Bag 692 contains 9 instances

(matrix([[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 np.int64(1))

In [11]:
def custom_collate_fn(batch):
    # Custom collate function to handle bags with variable number of instances
    instances, labels = zip(*batch)
    return instances, torch.tensor(labels[0], dtype=torch.float32).view(1)

In [12]:
dataloader = DataLoader(dataset, batch_size=16, shuffle=True, collate_fn=custom_collate_fn)
len(dataloader)

165

In [13]:
class Attention(nn.Module):
    def __init__(self):
        super(Attention, self).__init__()
        self.M = 500
        self.L = 128

        self.feature_extractor_part1 = nn.Sequential(
            nn.Linear(1, 128),  # 使用全连接层
            nn.ReLU(),
            nn.Linear(128, self.M),
            nn.ReLU()
        )

        self.attention = nn.Sequential(
            nn.Linear(self.M, self.L),  # matrix V
            nn.Tanh(),
            nn.Linear(self.L, 1)  # single attention weight
        )

        self.classifier = nn.Sequential(
            nn.Linear(self.M, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        H = self.feature_extractor_part1(x)
        A = self.attention(H)  # Kx1
        A = torch.transpose(A, 1, 0)  # 1xK
        A = F.softmax(A, dim=1)  # softmax over K

        Z = torch.mm(A, H)  # 1xM

        Y_prob = self.classifier(Z)
        Y_hat = torch.ge(Y_prob, 0.5).float()

        return Y_prob, Y_hat, A

In [14]:
class MIL(nn.Module):
    def __init__(self, input_dim):
        super(MIL, self).__init__()
        self.fc1 = nn.Linear(input_dim, 64)
        self.fc2 = nn.Linear(64, 32)
        self.fc3 = nn.Linear(32, 1)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        x = torch.sigmoid(self.fc3(x))
        return x

In [15]:
class MILAggregator(nn.Module):
    def __init__(self, input_dim):
        super(MILAggregator, self).__init__()
        self.mil = MIL(input_dim)
        self.attention = Attention()
        self.stored_weights = []

    def forward(self, bag):
        # Process each instance in the bag
        instance_outputs = torch.stack([self.mil(instance) for instance in bag])

        # Reshape instance_outputs to (num_instances, 1)
        instance_outputs = instance_outputs.view(-1, 1)

        # Debug print
        #print("instance_outputs shape:", instance_outputs.shape)

        # Calculate attention weights
        Y_prob, Y_hat, weights = self.attention(instance_outputs)
        
        # Debug print
        #print("weights shape:", weights.shape)
        #print("instance_outputs shape after attention:", instance_outputs.shape)
        
        # Aggregate the instance outputs using attention weights
        bag_output = torch.sum(weights * instance_outputs.T, dim=1, keepdim=True)

        self.stored_weights.append(weights.detach().cpu().numpy())
        
        # Debug print
        #print("bag_output shape before view:", bag_output.shape)

        return bag_output.view(1)  # Ensure the output shape is a scalar
    
    def get_stored_weights(self):
        return self.stored_weights
    
    def clear_stored_weights(self):
        self.stored_weights = []

In [16]:
model= MILAggregator(adata.n_vars)
model.to(device)

MILAggregator(
  (mil): MIL(
    (fc1): Linear(in_features=19379, out_features=64, bias=True)
    (fc2): Linear(in_features=64, out_features=32, bias=True)
    (fc3): Linear(in_features=32, out_features=1, bias=True)
  )
  (attention): Attention(
    (feature_extractor_part1): Sequential(
      (0): Linear(in_features=1, out_features=128, bias=True)
      (1): ReLU()
      (2): Linear(in_features=128, out_features=500, bias=True)
      (3): ReLU()
    )
    (attention): Sequential(
      (0): Linear(in_features=500, out_features=128, bias=True)
      (1): Tanh()
      (2): Linear(in_features=128, out_features=1, bias=True)
    )
    (classifier): Sequential(
      (0): Linear(in_features=500, out_features=1, bias=True)
      (1): Sigmoid()
    )
  )
)

In [17]:
criterion = nn.BCELoss().to(device)
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [18]:
num_epochs = 10

for epoch in range(num_epochs):
    model.train()
    running_loss = 0.0

    for i, (instances, label) in enumerate(dataloader):
        instances = [torch.tensor(np.array(instance), dtype=torch.float32).to(device) for instance in instances[0]]
        label = torch.tensor(label, dtype=torch.float32).to(device)

        optimizer.zero_grad()

       
        output = model(instances)


        loss = criterion(output, label)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

        if i % 10 == 9:  
            print(f"Epoch [{epoch+1}/{num_epochs}], Step [{i+1}], Loss: {loss.item():.4f}")

    print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {running_loss / len(dataloader):.4f}")

print("Finished Training")

/tmp/ipykernel_52482/2076624706.py:9: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  label = torch.tensor(label, dtype=torch.float32).to(device)

Epoch [1/10], Step [10], Loss: 0.0015
Epoch [1/10], Step [20], Loss: 1.0550
Epoch [1/10], Step [30], Loss: 1.2601
Epoch [1/10], Step [40], Loss: 0.1122
Epoch [1/10], Step [50], Loss: 0.0937
Epoch [1/10], Step [60], Loss: 0.4024
Epoch [1/10], Step [70], Loss: 1.7970
Epoch [1/10], Step [80], Loss: 0.0937
Epoch [1/10], Step [90], Loss: 0.3625
Epoch [1/10], Step [100], Loss: 1.5140
Epoch [1/10], Step [110], Loss: 0.1406
Epoch [1/10], Step [120], Loss: 0.6578
Epoch [1/10], Step [130], Loss: 0.8818
Epoch [1/10], Step [140], Loss: 0.5066
Epoch [1/10], Step [150], Loss: 0.8036
Epoch [1/10], Step [160], Loss: 0.3417
Epoch [1/10], Loss: 0.8681
Epoch [2/10], Step [10], Loss: 0.0625
Epoch [2/10], Step [20], Loss: 0.6838
Epoch [2/10], Step [30], Loss: 0.8119
Epoch [2/10], Step [40], Loss: 0.7201
Epoch [2/10], Step [50], Loss: 0.6458
Epoch [2/10], Step [60], Loss: 0.6347
Epoch [2/10], Step [70], Loss: 0.4626
Epoch [2/10], Step [80], Loss: 0.2303
Epoch [2/10], Step [90], Loss: 0.6848
Epoch [2/10], Step [100], Loss: 0.7544
Epoch [2/10], Step [110], Loss: 0.8254
Epoch [2/10], Step [120], Loss: 0.5130
Epoch [2/10], Step [130], Loss: 0.6722
Epoch [2/10], Step [140], Loss: 0.8041
Epoch [2/10], Step [150], Loss: 0.5482
Epoch [2/10], Step [160], Loss: 0.5223
Epoch [2/10], Loss: 0.7054
Epoch [3/10], Step [10], Loss: 0.9632
Epoch [3/10], Step [20], Loss: 0.9194
Epoch [3/10], Step [30], Loss: 0.8617
Epoch [3/10], Step [40], Loss: 0.6419
Epoch [3/10], Step [50], Loss: 0.6597
Epoch [3/10], Step [60], Loss: 0.6587
Epoch [3/10], Step [70], Loss: 0.6503
Epoch [3/10], Step [80], Loss: 0.7372
Epoch [3/10], Step [90], Loss: 0.6465
Epoch [3/10], Step [100], Loss: 0.7429
Epoch [3/10], Step [110], Loss: 0.7583
Epoch [3/10], Step [120], Loss: 0.6438
Epoch [3/10], Step [130], Loss: 0.6155
Epoch [3/10], Step [140], Loss: 0.6380
Epoch [3/10], Step [150], Loss: 0.6431
Epoch [3/10], Step [160], Loss: 0.6594
Epoch [3/10], Loss: 0.6971
Epoch [4/10], Step [10], Loss: 0.6564
Epoch [4/10], Step [20], Loss: 0.6508
Epoch [4/10], Step [30], Loss: 0.7340
Epoch [4/10], Step [40], Loss: 0.6539
Epoch [4/10], Step [50], Loss: 0.6449
Epoch [4/10], Step [60], Loss: 0.6327
Epoch [4/10], Step [70], Loss: 0.7382
Epoch [4/10], Step [80], Loss: 0.7540
Epoch [4/10], Step [90], Loss: 0.6345
Epoch [4/10], Step [100], Loss: 0.7382
Epoch [4/10], Step [110], Loss: 0.7504
Epoch [4/10], Step [120], Loss: 0.6415
Epoch [4/10], Step [130], Loss: 0.7485
Epoch [4/10], Step [140], Loss: 0.6509
Epoch [4/10], Step [150], Loss: 0.7399
Epoch [4/10], Step [160], Loss: 0.7335
Epoch [4/10], Loss: 0.6954
Epoch [5/10], Step [10], Loss: 0.7499
Epoch [5/10], Step [20], Loss: 0.7331
Epoch [5/10], Step [30], Loss: 0.7423
Epoch [5/10], Step [40], Loss: 0.6574
Epoch [5/10], Step [50], Loss: 0.7380
Epoch [5/10], Step [60], Loss: 0.0009
Epoch [5/10], Step [70], Loss: 0.1103
Epoch [5/10], Step [80], Loss: 1.3461
Epoch [5/10], Step [90], Loss: 0.6567
Epoch [5/10], Step [100], Loss: 0.6554
Epoch [5/10], Step [110], Loss: 0.7140
Epoch [5/10], Step [120], Loss: 0.6544
Epoch [5/10], Step [130], Loss: 0.6479
Epoch [5/10], Step [140], Loss: 0.6451
Epoch [5/10], Step [150], Loss: 0.7487
Epoch [5/10], Step [160], Loss: 0.7529
Epoch [5/10], Loss: 0.7184
Epoch [6/10], Step [10], Loss: 0.9084
Epoch [6/10], Step [20], Loss: 0.7590
Epoch [6/10], Step [30], Loss: 0.6281
Epoch [6/10], Step [40], Loss: 0.7711
Epoch [6/10], Step [50], Loss: 0.7738
Epoch [6/10], Step [60], Loss: 0.6184
Epoch [6/10], Step [70], Loss: 0.7780
Epoch [6/10], Step [80], Loss: 0.7767
Epoch [6/10], Step [90], Loss: 0.7751
Epoch [6/10], Step [100], Loss: 0.6210
Epoch [6/10], Step [110], Loss: 0.7653
Epoch [6/10], Step [120], Loss: 0.6245
Epoch [6/10], Step [130], Loss: 0.6204
Epoch [6/10], Step [140], Loss: 0.7723
Epoch [6/10], Step [150], Loss: 0.7704
Epoch [6/10], Step [160], Loss: 0.6251
Epoch [6/10], Loss: 0.6919
Epoch [7/10], Step [10], Loss: 0.7569
Epoch [7/10], Step [20], Loss: 0.6346
Epoch [7/10], Step [30], Loss: 0.6351
Epoch [7/10], Step [40], Loss: 0.6322
Epoch [7/10], Step [50], Loss: 0.6343
Epoch [7/10], Step [60], Loss: 0.6248
Epoch [7/10], Step [70], Loss: 0.7695
Epoch [7/10], Step [80], Loss: 0.6211
Epoch [7/10], Step [90], Loss: 0.6187
Epoch [7/10], Step [100], Loss: 0.7741
Epoch [7/10], Step [110], Loss: 0.6230
Epoch [7/10], Step [120], Loss: 0.7463
Epoch [7/10], Step [130], Loss: 0.7677
Epoch [7/10], Step [140], Loss: 0.6302
Epoch [7/10], Step [150], Loss: 0.6240
Epoch [7/10], Step [160], Loss: 0.7688
Epoch [7/10], Loss: 0.6906
Epoch [8/10], Step [10], Loss: 0.7675
Epoch [8/10], Step [20], Loss: 0.6237
Epoch [8/10], Step [30], Loss: 0.7670
Epoch [8/10], Step [40], Loss: 0.6261
Epoch [8/10], Step [50], Loss: 0.7674
Epoch [8/10], Step [60], Loss: 0.7673
Epoch [8/10], Step [70], Loss: 0.7682
Epoch [8/10], Step [80], Loss: 0.6221
Epoch [8/10], Step [90], Loss: 0.6161
Epoch [8/10], Step [100], Loss: 0.7797
Epoch [8/10], Step [110], Loss: 0.6130
Epoch [8/10], Step [120], Loss: 0.6128
Epoch [8/10], Step [130], Loss: 0.6161
Epoch [8/10], Step [140], Loss: 0.6194
Epoch [8/10], Step [150], Loss: 0.7723
Epoch [8/10], Step [160], Loss: 0.7680
Epoch [8/10], Loss: 0.6924
Epoch [9/10], Step [10], Loss: 0.6264
Epoch [9/10], Step [20], Loss: 0.6275
Epoch [9/10], Step [30], Loss: 0.7623
Epoch [9/10], Step [40], Loss: 0.7582
Epoch [9/10], Step [50], Loss: 0.6370
Epoch [9/10], Step [60], Loss: 0.7494
Epoch [9/10], Step [70], Loss: 0.6419
Epoch [9/10], Step [80], Loss: 0.6416
Epoch [9/10], Step [90], Loss: 0.7487
Epoch [9/10], Step [100], Loss: 0.6440
Epoch [9/10], Step [110], Loss: 0.6453
Epoch [9/10], Step [120], Loss: 0.7447
Epoch [9/10], Step [130], Loss: 0.6455
Epoch [9/10], Step [140], Loss: 0.7446
Epoch [9/10], Step [150], Loss: 0.6439
Epoch [9/10], Step [160], Loss: 0.7473
Epoch [9/10], Loss: 0.6962
Epoch [10/10], Step [10], Loss: 0.6457
Epoch [10/10], Step [20], Loss: 0.6452
Epoch [10/10], Step [30], Loss: 0.7461
Epoch [10/10], Step [40], Loss: 0.7452
Epoch [10/10], Step [50], Loss: 0.7407
Epoch [10/10], Step [60], Loss: 0.6510
Epoch [10/10], Step [70], Loss: 0.7344
Epoch [10/10], Step [80], Loss: 0.6565
Epoch [10/10], Step [90], Loss: 0.6594
Epoch [10/10], Step [100], Loss: 0.6582
Epoch [10/10], Step [110], Loss: 0.7328
Epoch [10/10], Step [120], Loss: 0.7346
Epoch [10/10], Step [130], Loss: 0.6558
Epoch [10/10], Step [140], Loss: 0.6556
Epoch [10/10], Step [150], Loss: 0.6553
Epoch [10/10], Step [160], Loss: 0.6525
Epoch [10/10], Loss: 0.6935
Finished Training

In [19]:
torch.save(model.state_dict(), 'mil_aggregator.pth')

In [20]:
def evaluate_model(model, dataloader, device):
    model.eval()
    total = 0
    correct = 0
    all_stored_weights = []

    with torch.no_grad():
        for idx, (instances, label) in enumerate(dataloader):
            instances = [torch.tensor(np.array(instance), dtype=torch.float32).to(device) for instance in instances[0]]
            label = torch.tensor(label, dtype=torch.float32).to(device)

            output = model(instances)
            predicted = (output > 0.5).float()
            total += label.size(0)
            correct += (predicted == label).sum().item()

            stored_weights = model.get_stored_weights()
            all_stored_weights.append(stored_weights)
            model.clear_stored_weights() 

    accuracy = 100 * correct / total
    print(f'Accuracy of the model on the entire dataset: {accuracy}%')

    for i, stored_weights in enumerate(all_stored_weights):
        for j, weights in enumerate(stored_weights):
            print(f"Data point {i}, Bag {j} weights: {weights}")

In [23]:
test_dataloader = DataLoader(dataset, batch_size=1, shuffle=True, collate_fn=custom_collate_fn)

In [24]:
evaluate_model(model, list(test_dataloader)[0:1], device)

Accuracy of the model on the entire dataset: 0.0%
Data point 0, Bag 0 weights: [[1.1829333e-06 1.4285684e-01 1.4285684e-01 1.4285684e-01 1.4285684e-01
  1.0520686e-06 1.4285684e-01 1.4285684e-01 1.4285684e-01]]

/tmp/ipykernel_52482/208287778.py:10: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  label = torch.tensor(label, dtype=torch.float32).to(device)