In [2]:
import torch
from torch.utils.data import DataLoader, TensorDataset, random_split
from collections import OrderedDict
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import scanpy as sc
import numpy as np
import pandas as pd
from torchsummary import summary
from torchviz import make_dot
from tqdm import tqdm
from sklearn.metrics import roc_auc_score
import csv
from scipy.sparse import issparse



from model.dataset import BagsDataset, custom_collate_fn
from  model.model import MIL, EarlyStopping
from model.dataset import BagsDataset, custom_collate_fn

In [3]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
if device.type == "cuda":
    gpu_name = torch.cuda.get_device_name(torch.cuda.current_device())
    print(f"Using device: {device} ({gpu_name})")
else:
    print(f"Using device: {device}")

Using device: cpu

In [4]:
all_genes = pd.read_csv('tumor_antigen.csv')
all_genes = all_genes['Gene'].values
dataset = BagsDataset('training.csv', immune_cell='tcell')
#adata = sc.read_h5ad('../test.h5ad')
#dataset = BagsDataset(adata, immune_cell='tcell',radius=200, resolution='low')
train_size = int(0.7 * len(dataset))
val_size = len(dataset) - train_size
train_dataset, val_dataset = random_split(dataset, [train_size, val_size])

Processing: adata=HumanLungCancerFFPE.h5ad, radius=200, resolution=low

Creating Bags with radius 200: 100%|█████████████████████████| 3858/3858 [00:00<00:00, 21454.95it/s]

Total bags created: 1333
Average instances per bag: 7

In [5]:
dataloader = torch.utils.data.DataLoader(train_dataset, batch_size=1, shuffle=True, collate_fn=custom_collate_fn)
val_dataloader = torch.utils.data.DataLoader(val_dataset, batch_size=1, shuffle=True, collate_fn=custom_collate_fn)

In [7]:
model = MIL(all_genes).to(device)
criterion = nn.BCELoss().to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.0001)

In [8]:
num_epochs = 1000
patience = 5
early_stopping = EarlyStopping(patience=patience, delta=0.0001)

In [9]:
ig_scores_before_training = torch.sigmoid(model.immunogenicity.ig)
with open('ig_scores_before_training.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(['Gene', 'IG Score Before Training'])
    for gene, score in zip(all_genes, ig_scores_before_training):
        writer.writerow([gene, score.item()])

In [10]:
for epoch in range(num_epochs):
    model.train() 
    running_loss = 0.0
    
    with tqdm(dataloader, unit="batch") as tepoch:
        for i, (distances, gene_expressions, label, core_idx, current_genes) in enumerate(tepoch):
            tepoch.set_description(f"Epoch {epoch+1}/{num_epochs}")

            optimizer.zero_grad()

            distances = torch.stack(distances).to(device)
            gene_expressions = torch.stack(gene_expressions).to(device)
            label = label.clone().detach().float().to(device)
            
            output = model(distances, gene_expressions, list(current_genes[0]))
            
            loss = criterion(output, label)
            loss.backward()
            optimizer.step()

            running_loss += loss.item()
            tepoch.set_postfix(loss=loss.item())

    epoch_loss = running_loss / len(dataloader)
    print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {epoch_loss:.4f}')
    

    model.eval()
    val_loss = 0.0
    all_labels = []
    all_outputs = []
    with torch.no_grad():
        for val_distances, val_gene_expressions, val_label, _, val_current_genes in val_dataloader:
            val_distances = torch.stack(val_distances).to(device)
            val_gene_expressions = torch.stack(val_gene_expressions).to(device)
            val_label = val_label.clone().detach().float().to(device)
            val_output = model(val_distances, val_gene_expressions, list(val_current_genes[0]))
            val_loss += criterion(val_output, val_label).item()
            all_labels.extend(val_label.cpu().numpy())
            all_outputs.extend(val_output.cpu().numpy())
    val_loss /= len(val_dataloader)
    val_auroc = roc_auc_score(all_labels, all_outputs)
    print(f'Validation Loss: {val_loss:.4f}, Validation AUROC: {val_auroc:.4f}')


    early_stopping(val_loss, model, epoch)
    if early_stopping.early_stop:
        print(f'Early stopping at epoch {epoch+1}')
        break

Epoch 1/1000:   8%|▊         | 79/933 [00:00<00:02, 391.11batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([6.3803e-12], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.2498e-29], grad_fn=<SumBackward1>)
bag_output: tensor([4.4933e-39], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 1/1000:  13%|█▎        | 122/933 [00:00<00:02, 405.37batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([6.8092e-38], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.2498e-29], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 1/1000:  22%|██▏       | 208/933 [00:00<00:01, 411.63batch/s, loss=0.693]

bag_output: tensor([2.9650e-40], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 1/1000:  31%|███▏      | 292/933 [00:00<00:01, 412.51batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([7.7367e-31], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([6.1834e-25], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([2.3698e-34], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 1/1000:  40%|████      | 376/933 [00:01<00:01, 405.94batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([7.8186e-36], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.2497e-29], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 1/1000:  49%|████▉     | 461/933 [00:01<00:01, 402.40batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.2098e-16], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([4.4933e-39], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([8.5479e-44], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 1/1000:  58%|█████▊    | 544/933 [00:01<00:00, 406.52batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([2.9650e-40], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.8858e-28], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([3.5746e-33], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 1/1000:  67%|██████▋   | 626/933 [00:01<00:00, 403.48batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([4.4934e-39], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([4.3495e-26], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 1/1000:  76%|███████▌  | 707/933 [00:01<00:00, 389.03batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.4825e-40], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.2850e-42], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 1/1000:  84%|████████▍ | 785/933 [00:02<00:00, 387.16batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.4669e-35], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.0274e-36], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([5.6052e-45], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 1/1000:  92%|█████████▏| 863/933 [00:02<00:00, 379.24batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([8.2470e-31], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 1/1000: 100%|██████████| 933/933 [00:02<00:00, 395.63batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.0166], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([2.0805e-41], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
Epoch [1/1000], Loss: 0.6931
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([2.5106e-21])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([3.5330e-40])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([5.7049e-19])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([7.9922e-39])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([3.7514e-20])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([1.4602e-42])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([6.2461e-32])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([8.0279e-38])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([3.5330e-40])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([1.4588e-42])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([7.0065e-45])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([6.2480e-32])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([8.8321e-31])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.2693])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
Validation Loss: 0.6935, Validation AUROC: 0.4962

Epoch 2/1000:   4%|▍         | 39/933 [00:00<00:02, 382.68batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([2.7867e-34], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([3.6983e-40], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 2/1000:   4%|▍         | 39/933 [00:00<00:02, 382.68batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 2/1000:  13%|█▎        | 124/933 [00:00<00:01, 413.48batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.0930e-43], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.8499e-40], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 2/1000:  13%|█▎        | 124/933 [00:00<00:01, 413.48batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 2/1000:  22%|██▏       | 206/933 [00:00<00:01, 394.83batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.4707e-29], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 2/1000:  22%|██▏       | 206/933 [00:00<00:01, 394.83batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.4681e-29], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 2/1000:  31%|███       | 288/933 [00:00<00:01, 395.27batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([4.2919e-33], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 2/1000:  31%|███       | 288/933 [00:00<00:01, 395.27batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 2/1000:  40%|███▉      | 370/933 [00:00<00:01, 401.74batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([9.7529e-31], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([7.0065e-45], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 2/1000:  40%|███▉      | 370/933 [00:01<00:01, 401.74batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 2/1000:  49%|████▉     | 455/933 [00:01<00:01, 408.72batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([3.6997e-40], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 2/1000:  49%|████▉     | 455/933 [00:01<00:01, 408.72batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([7.0809e-25], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.6283e-42], grad_fn=<SumBackward1>)
bag_output: tensor([9.4977e-36], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 2/1000:  58%|█████▊    | 539/933 [00:01<00:00, 412.57batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([9.1619e-31], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 2/1000:  58%|█████▊    | 539/933 [00:01<00:00, 412.57batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 2/1000:  67%|██████▋   | 623/933 [00:01<00:00, 407.65batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.7812e-35], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([5.5793e-39], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 2/1000:  67%|██████▋   | 623/933 [00:01<00:00, 407.65batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 2/1000:  75%|███████▌  | 704/933 [00:01<00:00, 391.62batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([2.4579e-41], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.0168], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([6.8812e-12], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([6.7806e-39], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.0155e-37], grad_fn=<SumBackward1>)
bag_output: tensor([1.4307e-16], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 2/1000:  75%|███████▌  | 704/933 [00:01<00:00, 391.62batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 2/1000:  84%|████████▍ | 784/933 [00:01<00:00, 392.83batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([2.5497e-28], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([6.8048e-39], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 2/1000:  84%|████████▍ | 784/933 [00:02<00:00, 392.83batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 2/1000:  93%|█████████▎| 866/933 [00:02<00:00, 391.18batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.5159e-36], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 2/1000:  93%|█████████▎| 866/933 [00:02<00:00, 391.18batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 2/1000: 100%|██████████| 933/933 [00:02<00:00, 398.64batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.7062e-29], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([5.7112e-26], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.4013e-45], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
Epoch [2/1000], Loss: 0.6931
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([1.0179e-37])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.2699])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([7.6224e-32])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([2.8597e-21])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([1.9058e-42])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([8.4078e-45])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([1.0219e-38])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([1.9128e-42])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([1.0691e-30])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([7.6247e-32])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([6.3993e-19])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([4.2399e-20])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([4.5489e-40])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([1.4013e-45])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([4.5489e-40])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
Validation Loss: 0.6935, Validation AUROC: 0.4962

Epoch 3/1000:   0%|          | 0/933 [00:00<?, ?batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 3/1000:   5%|▍         | 42/933 [00:00<00:02, 409.27batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 3/1000:   5%|▍         | 42/933 [00:00<00:02, 409.27batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.0729e-30], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 3/1000:   9%|▉         | 84/933 [00:00<00:02, 411.26batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.4013e-45], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 3/1000:  14%|█▎        | 126/933 [00:00<00:02, 390.48batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 3/1000:  14%|█▎        | 126/933 [00:00<00:02, 390.48batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 3/1000:  18%|█▊        | 167/933 [00:00<00:01, 396.91batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([6.8048e-39], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.3593e-43], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 3/1000:  22%|██▏       | 207/933 [00:00<00:01, 393.37batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([2.0305e-42], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 3/1000:  22%|██▏       | 207/933 [00:00<00:01, 393.37batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([7.1704e-12], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 3/1000:  27%|██▋       | 248/933 [00:00<00:01, 396.38batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([5.0907e-33], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.7122e-29], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 3/1000:  31%|███       | 289/933 [00:00<00:01, 398.73batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 3/1000:  31%|███       | 289/933 [00:00<00:01, 398.73batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.4013e-45], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([2.2745e-40], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 3/1000:  35%|███▌      | 330/933 [00:00<00:01, 401.44batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.1405e-30], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 3/1000:  40%|███▉      | 371/933 [00:00<00:01, 392.10batch/s, loss=0.693]

bag_output: tensor([1.7061e-29], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.1389e-35], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([4.5489e-40], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 3/1000:  40%|███▉      | 371/933 [00:01<00:01, 392.10batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.7062e-29], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 3/1000:  44%|████▍     | 411/933 [00:01<00:01, 384.88batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.5159e-36], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 3/1000:  48%|████▊     | 450/933 [00:01<00:01, 372.80batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([5.7112e-26], grad_fn=<SumBackward1>)

Epoch 3/1000:  48%|████▊     | 450/933 [00:01<00:01, 372.80batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 3/1000:  52%|█████▏    | 489/933 [00:01<00:01, 376.16batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([8.0361e-25], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([2.5498e-28], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 3/1000:  52%|█████▏    | 489/933 [00:01<00:01, 376.16batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 3/1000:  56%|█████▋    | 527/933 [00:01<00:01, 375.74batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.4320e-16], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([3.4074e-34], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 3/1000:  61%|██████    | 565/933 [00:01<00:00, 370.76batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 3/1000:  61%|██████    | 565/933 [00:01<00:00, 370.76batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 3/1000:  65%|██████▍   | 605/933 [00:01<00:00, 376.69batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 3/1000:  69%|██████▉   | 643/933 [00:01<00:00, 374.49batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 3/1000:  69%|██████▉   | 643/933 [00:01<00:00, 374.49batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 3/1000:  73%|███████▎  | 681/933 [00:01<00:00, 365.80batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 3/1000:  77%|███████▋  | 720/933 [00:01<00:00, 370.46batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([6.8286e-39], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.0169], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.1210e-44], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 3/1000:  77%|███████▋  | 720/933 [00:01<00:00, 370.46batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 3/1000:  81%|████████▏ | 759/933 [00:02<00:00, 373.77batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 3/1000:  86%|████████▌ | 798/933 [00:02<00:00, 376.59batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([8.4552e-39], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 3/1000:  86%|████████▌ | 798/933 [00:02<00:00, 376.59batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([3.8091e-41], grad_fn=<SumBackward1>)

Epoch 3/1000:  90%|████████▉ | 836/933 [00:02<00:00, 374.49batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.2500e-37], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 3/1000:  94%|█████████▍| 876/933 [00:02<00:00, 380.37batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([2.5863e-35], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 3/1000:  94%|█████████▍| 876/933 [00:02<00:00, 380.37batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 3/1000:  98%|█████████▊| 915/933 [00:02<00:00, 382.81batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([5.6606e-40], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 3/1000: 100%|██████████| 933/933 [00:02<00:00, 383.27batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
Epoch [3/1000], Loss: 0.6931
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([2.4144e-42])
bag_output: tensor([0.])
bag_output: tensor([1.2611e-30])
bag_output: tensor([0.])
bag_output: tensor([2.4018e-42])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.2704])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([9.0551e-32])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([3.2006e-21])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([1.4013e-45])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([5.6605e-40])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([5.6604e-40])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([7.0679e-19])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([4.7134e-20])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([1.1210e-44])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([9.0578e-32])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([1.2500e-37])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([1.2640e-38])
bag_output: tensor([0.])
bag_output: tensor([0.])
Validation Loss: 0.6935, Validation AUROC: 0.4962

Epoch 4/1000:   0%|          | 0/933 [00:00<?, ?batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([6.0983e-33], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:   0%|          | 0/933 [00:00<?, ?batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([7.6109e-12], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([5.6604e-40], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.0170], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:   5%|▍         | 43/933 [00:00<00:02, 420.27batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.4013e-45], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.4013e-45], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:   5%|▍         | 43/933 [00:00<00:02, 420.27batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:   9%|▉         | 86/933 [00:00<00:02, 418.83batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:   9%|▉         | 86/933 [00:00<00:02, 418.83batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  14%|█▎        | 128/933 [00:00<00:02, 358.93batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  14%|█▎        | 128/933 [00:00<00:02, 358.93batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  18%|█▊        | 170/933 [00:00<00:02, 378.72batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.5487e-30], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.0290e-24], grad_fn=<SumBackward1>)

Epoch 4/1000:  18%|█▊        | 170/933 [00:00<00:02, 378.72batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  22%|██▏       | 209/933 [00:00<00:01, 376.00batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.0135e-38], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.0066e-38], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.4604e-30], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  22%|██▏       | 209/933 [00:00<00:01, 376.00batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  22%|██▏       | 209/933 [00:00<00:01, 376.00batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  27%|██▋       | 248/933 [00:00<00:01, 373.55batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  31%|███       | 287/933 [00:00<00:01, 376.02batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([3.0422e-35], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([7.3845e-26], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([2.1880e-36], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  31%|███       | 287/933 [00:00<00:01, 376.02batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  31%|███       | 287/933 [00:00<00:01, 376.02batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  35%|███▍      | 326/933 [00:00<00:01, 377.27batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  39%|███▉      | 366/933 [00:01<00:01, 383.47batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([2.2885e-29], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([2.2886e-29], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  39%|███▉      | 366/933 [00:01<00:01, 383.47batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  39%|███▉      | 366/933 [00:01<00:01, 383.47batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([3.3894e-28], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  43%|████▎     | 405/933 [00:01<00:01, 384.39batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  48%|████▊     | 444/933 [00:01<00:01, 376.57batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([6.8120e-40], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  48%|████▊     | 444/933 [00:01<00:01, 376.57batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  48%|████▊     | 444/933 [00:01<00:01, 376.57batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  52%|█████▏    | 482/933 [00:01<00:01, 366.50batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([3.4060e-40], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  56%|█████▌    | 519/933 [00:01<00:01, 352.80batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([3.1263e-42], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  56%|█████▌    | 519/933 [00:01<00:01, 352.80batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  56%|█████▌    | 519/933 [00:01<00:01, 352.80batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  59%|█████▉    | 555/933 [00:01<00:01, 344.18batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  59%|█████▉    | 555/933 [00:01<00:01, 344.18batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([2.3042e-29], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  63%|██████▎   | 590/933 [00:01<00:01, 342.27batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  63%|██████▎   | 590/933 [00:01<00:01, 342.27batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  67%|██████▋   | 625/933 [00:01<00:00, 344.09batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  67%|██████▋   | 625/933 [00:01<00:00, 344.09batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  71%|███████   | 660/933 [00:01<00:00, 342.29batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  71%|███████   | 660/933 [00:01<00:00, 342.29batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  75%|███████▍  | 699/933 [00:01<00:00, 355.73batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.4875e-37], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  75%|███████▍  | 699/933 [00:02<00:00, 355.73batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  79%|███████▉  | 739/933 [00:02<00:00, 366.42batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  79%|███████▉  | 739/933 [00:02<00:00, 366.42batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  79%|███████▉  | 739/933 [00:02<00:00, 366.42batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  83%|████████▎ | 777/933 [00:02<00:00, 367.72batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([4.6099e-41], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  87%|████████▋ | 814/933 [00:02<00:00, 364.25batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  87%|████████▋ | 814/933 [00:02<00:00, 364.25batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  87%|████████▋ | 814/933 [00:02<00:00, 364.25batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.6789e-16], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.0135e-38], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  91%|█████████ | 851/933 [00:02<00:00, 360.94batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([2.1300e-43], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.6240e-35], grad_fn=<SumBackward1>)

Epoch 4/1000:  95%|█████████▌| 888/933 [00:02<00:00, 362.69batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  95%|█████████▌| 888/933 [00:02<00:00, 362.69batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.4013e-44], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000:  95%|█████████▌| 888/933 [00:02<00:00, 362.69batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 4/1000: 100%|██████████| 933/933 [00:02<00:00, 366.23batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([4.7997e-34], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
Epoch [4/1000], Loss: 0.6931
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([2.9413e-42])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([1.4505e-30])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([6.8120e-40])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([1.0481e-31])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([2.9217e-42])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([5.1557e-20])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([1.4013e-44])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([1.4875e-37])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([6.8120e-40])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([1.0477e-31])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([7.6886e-19])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([1.5134e-38])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.2708])
bag_output: tensor([3.5210e-21])
bag_output: tensor([0.])
bag_output: tensor([1.4013e-45])
Validation Loss: 0.6935, Validation AUROC: 0.4962

Epoch 5/1000:   0%|          | 0/933 [00:00<?, ?batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:   0%|          | 0/933 [00:00<?, ?batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:   4%|▍         | 39/933 [00:00<00:02, 382.24batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:   4%|▍         | 39/933 [00:00<00:02, 382.24batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:   4%|▍         | 39/933 [00:00<00:02, 382.24batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:   9%|▊         | 80/933 [00:00<00:02, 397.54batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:   9%|▊         | 80/933 [00:00<00:02, 397.54batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  13%|█▎        | 121/933 [00:00<00:02, 400.07batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([3.1263e-42], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  13%|█▎        | 121/933 [00:00<00:02, 400.07batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  17%|█▋        | 163/933 [00:00<00:01, 407.75batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  17%|█▋        | 163/933 [00:00<00:01, 407.75batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  17%|█▋        | 163/933 [00:00<00:01, 407.75batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([3.0422e-35], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.0066e-38], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  22%|██▏       | 205/933 [00:00<00:01, 410.46batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.6789e-16], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([6.8120e-40], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  22%|██▏       | 205/933 [00:00<00:01, 410.46batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.0135e-38], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  22%|██▏       | 205/933 [00:00<00:01, 410.46batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  27%|██▋       | 248/933 [00:00<00:01, 415.48batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  27%|██▋       | 248/933 [00:00<00:01, 415.48batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([2.1880e-36], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.0172], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  31%|███       | 290/933 [00:00<00:01, 414.34batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([5.7223e-34], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.8217e-44], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  31%|███       | 290/933 [00:00<00:01, 414.34batch/s, loss=0.693]

bag_output: tensor([3.9427e-28], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  31%|███       | 290/933 [00:00<00:01, 414.34batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  36%|███▌      | 332/933 [00:00<00:01, 415.13batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  36%|███▌      | 332/933 [00:00<00:01, 415.13batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  40%|████      | 374/933 [00:00<00:01, 416.50batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.8234e-30], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  40%|████      | 374/933 [00:00<00:01, 416.50batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  40%|████      | 374/933 [00:01<00:01, 416.50batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  45%|████▍     | 417/933 [00:01<00:01, 417.82batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  45%|████▍     | 417/933 [00:01<00:01, 417.82batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([8.4912e-33], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  49%|████▉     | 459/933 [00:01<00:01, 411.20batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.2513e-38], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.4013e-45], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  49%|████▉     | 459/933 [00:01<00:01, 411.20batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  49%|████▉     | 459/933 [00:01<00:01, 411.20batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  49%|████▉     | 459/933 [00:01<00:01, 411.20batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  54%|█████▎    | 501/933 [00:01<00:01, 404.72batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([8.4701e-26], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  58%|█████▊    | 543/933 [00:01<00:00, 409.17batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([8.4503e-40], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.9627e-35], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  58%|█████▊    | 543/933 [00:01<00:00, 409.17batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.1742e-24], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  58%|█████▊    | 543/933 [00:01<00:00, 409.17batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  58%|█████▊    | 543/933 [00:01<00:00, 409.17batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  63%|██████▎   | 586/933 [00:01<00:00, 412.84batch/s, loss=0.693]

bag_output: tensor([8.4898e-12], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  67%|██████▋   | 628/933 [00:01<00:00, 402.01batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([5.7561e-41], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  67%|██████▋   | 628/933 [00:01<00:00, 402.01batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  67%|██████▋   | 628/933 [00:01<00:00, 402.01batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  67%|██████▋   | 628/933 [00:01<00:00, 402.01batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  72%|███████▏  | 671/933 [00:01<00:00, 407.72batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  77%|███████▋  | 714/933 [00:01<00:00, 413.24batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  77%|███████▋  | 714/933 [00:01<00:00, 413.24batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  77%|███████▋  | 714/933 [00:01<00:00, 413.24batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([2.6769e-29], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.8213e-37], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  77%|███████▋  | 714/933 [00:01<00:00, 413.24batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  81%|████████  | 756/933 [00:01<00:00, 413.96batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([2.6905e-43], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  86%|████████▌ | 798/933 [00:01<00:00, 415.71batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([2.7000e-29], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.4013e-45], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  86%|████████▌ | 798/933 [00:01<00:00, 415.71batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  86%|████████▌ | 798/933 [00:02<00:00, 415.71batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  86%|████████▌ | 798/933 [00:02<00:00, 415.71batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  90%|█████████ | 841/933 [00:02<00:00, 419.29batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  95%|█████████▍| 883/933 [00:02<00:00, 412.96batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  95%|█████████▍| 883/933 [00:02<00:00, 412.96batch/s, loss=0.693]

bag_output: tensor([1.7219e-30], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  95%|█████████▍| 883/933 [00:02<00:00, 412.96batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000:  95%|█████████▍| 883/933 [00:02<00:00, 412.96batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([4.2252e-40], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 5/1000: 100%|██████████| 933/933 [00:02<00:00, 410.12batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([2.6769e-29], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
Epoch [5/1000], Loss: 0.6931
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([5.7228e-20])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([1.8217e-44])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([8.4503e-40])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.2713])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([8.4800e-19])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([8.4503e-40])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([1.4013e-45])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([3.7022e-42])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([1.2416e-31])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([3.6714e-42])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([3.9344e-21])
bag_output: tensor([1.2420e-31])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([1.8213e-37])
bag_output: tensor([0.])
bag_output: tensor([1.8662e-38])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([1.7071e-30])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
Validation Loss: 0.6935, Validation AUROC: 0.4962

Epoch 6/1000:   0%|          | 0/933 [00:00<?, ?batch/s, loss=0.693]

bag_output: tensor([4.2252e-40], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:   0%|          | 0/933 [00:00<?, ?batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:   0%|          | 0/933 [00:00<?, ?batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:   0%|          | 0/933 [00:00<?, ?batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:   5%|▍         | 43/933 [00:00<00:02, 424.79batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([8.4912e-33], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:   5%|▍         | 43/933 [00:00<00:02, 424.79batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.2513e-38], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:   5%|▍         | 43/933 [00:00<00:02, 424.79batch/s, loss=0.693]

bag_output: tensor([1.2406e-38], grad_fn=<SumBackward1>)

Epoch 6/1000:   5%|▍         | 43/933 [00:00<00:02, 424.79batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:   9%|▉         | 86/933 [00:00<00:02, 395.03batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.8234e-30], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:   9%|▉         | 86/933 [00:00<00:02, 395.03batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:   9%|▉         | 86/933 [00:00<00:02, 395.03batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([2.6769e-29], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  14%|█▎        | 126/933 [00:00<00:02, 381.23batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([5.7627e-34], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  14%|█▎        | 126/933 [00:00<00:02, 381.23batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  14%|█▎        | 126/933 [00:00<00:02, 381.23batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.8217e-44], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  18%|█▊        | 165/933 [00:00<00:02, 382.11batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.7219e-30], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  18%|█▊        | 165/933 [00:00<00:02, 382.11batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  18%|█▊        | 165/933 [00:00<00:02, 382.11batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.1742e-24], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  22%|██▏       | 204/933 [00:00<00:02, 357.04batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([8.4701e-26], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  22%|██▏       | 204/933 [00:00<00:02, 357.04batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  22%|██▏       | 204/933 [00:00<00:02, 357.04batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  22%|██▏       | 204/933 [00:00<00:02, 357.04batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  22%|██▏       | 204/933 [00:00<00:02, 357.04batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  26%|██▌       | 240/933 [00:00<00:02, 341.01batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  29%|██▉       | 275/933 [00:00<00:01, 330.13batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.9627e-35], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([8.4898e-12], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  29%|██▉       | 275/933 [00:00<00:01, 330.13batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  29%|██▉       | 275/933 [00:00<00:01, 330.13batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  29%|██▉       | 275/933 [00:00<00:01, 330.13batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  29%|██▉       | 275/933 [00:00<00:01, 330.13batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  33%|███▎      | 310/933 [00:00<00:01, 333.25batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.2513e-38], grad_fn=<SumBackward1>)

Epoch 6/1000:  37%|███▋      | 345/933 [00:01<00:01, 336.42batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  37%|███▋      | 345/933 [00:01<00:01, 336.42batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  37%|███▋      | 345/933 [00:01<00:01, 336.42batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  37%|███▋      | 345/933 [00:01<00:01, 336.42batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  37%|███▋      | 345/933 [00:01<00:01, 336.42batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  41%|████      | 383/933 [00:01<00:01, 346.91batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  45%|████▌     | 422/933 [00:01<00:01, 357.91batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([8.4503e-40], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  45%|████▌     | 422/933 [00:01<00:01, 357.91batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  45%|████▌     | 422/933 [00:01<00:01, 357.91batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  45%|████▌     | 422/933 [00:01<00:01, 357.91batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.8213e-37], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  45%|████▌     | 422/933 [00:01<00:01, 357.91batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  49%|████▉     | 459/933 [00:01<00:01, 359.46batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  53%|█████▎    | 496/933 [00:01<00:01, 362.16batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([2.6905e-43], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  53%|█████▎    | 496/933 [00:01<00:01, 362.16batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  53%|█████▎    | 496/933 [00:01<00:01, 362.16batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  53%|█████▎    | 496/933 [00:01<00:01, 362.16batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  53%|█████▎    | 496/933 [00:01<00:01, 362.16batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  57%|█████▋    | 534/933 [00:01<00:01, 366.02batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.4013e-45], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  62%|██████▏   | 575/933 [00:01<00:00, 377.22batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  62%|██████▏   | 575/933 [00:01<00:00, 377.22batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  62%|██████▏   | 575/933 [00:01<00:00, 377.22batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  62%|██████▏   | 575/933 [00:01<00:00, 377.22batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  62%|██████▏   | 575/933 [00:01<00:00, 377.22batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  66%|██████▌   | 615/933 [00:01<00:00, 382.62batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  70%|███████   | 654/933 [00:01<00:00, 373.89batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([3.6750e-35], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  70%|███████   | 654/933 [00:01<00:00, 373.89batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  70%|███████   | 654/933 [00:01<00:00, 373.89batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  70%|███████   | 654/933 [00:01<00:00, 373.89batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  70%|███████   | 654/933 [00:01<00:00, 373.89batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([3.9348e-42], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  74%|███████▍  | 692/933 [00:01<00:00, 374.52batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([2.6769e-29], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  78%|███████▊  | 730/933 [00:02<00:00, 375.68batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([3.9455e-28], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  78%|███████▊  | 730/933 [00:02<00:00, 375.68batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  78%|███████▊  | 730/933 [00:02<00:00, 375.68batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  78%|███████▊  | 730/933 [00:02<00:00, 375.68batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.8277e-16], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  78%|███████▊  | 730/933 [00:02<00:00, 375.68batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  82%|████████▏ | 768/933 [00:02<00:00, 373.85batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  86%|████████▋ | 806/933 [00:02<00:00, 374.57batch/s, loss=0.693]

bag_output: tensor([2.6615e-36], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([8.4503e-40], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  86%|████████▋ | 806/933 [00:02<00:00, 374.57batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  86%|████████▋ | 806/933 [00:02<00:00, 374.57batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  86%|████████▋ | 806/933 [00:02<00:00, 374.57batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  86%|████████▋ | 806/933 [00:02<00:00, 374.57batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  90%|█████████ | 844/933 [00:02<00:00, 371.47batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  95%|█████████▍| 884/933 [00:02<00:00, 378.83batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.0173], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  95%|█████████▍| 884/933 [00:02<00:00, 378.83batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  95%|█████████▍| 884/933 [00:02<00:00, 378.83batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  95%|█████████▍| 884/933 [00:02<00:00, 378.83batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000:  95%|█████████▍| 884/933 [00:02<00:00, 378.83batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)

Epoch 6/1000: 100%|██████████| 933/933 [00:02<00:00, 368.68batch/s, loss=0.693]

bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([7.3715e-41], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([1.4013e-45], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([3.2225e-29], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
bag_output: tensor([0.], grad_fn=<SumBackward1>)
Epoch [6/1000], Loss: 0.6931
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([4.7364e-42])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([2.0475e-30])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([1.5008e-31])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([2.3583e-38])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([1.4013e-45])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([1.0750e-39])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([1.0750e-39])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([2.3822e-44])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([9.4602e-19])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([2.2832e-37])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([4.4537e-21])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([6.4302e-20])
bag_output: tensor([0.])
bag_output: tensor([4.7854e-42])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.2718])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([1.5013e-31])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
bag_output: tensor([0.])
Validation Loss: 0.6935, Validation AUROC: 0.4962
Early stopping at epoch 6

In [125]:
ig_scores_after_training = torch.sigmoid(model.immunogenicity.ig)
ig_score = {
    'Gene': all_genes,
    'IG Score Before Training': [score.item() for score in ig_scores_before_training],
    'IG Score After Training': [score.item() for score in ig_scores_after_training]
}  
df = pd.DataFrame(ig_score)

In [123]:

# Calculate the difference and add it as a new column
df['Difference'] = df['IG Score After Training'] - df['IG Score Before Training']

/tmp/ipykernel_216404/3660844667.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Difference'] = df['IG Score After Training'] - df['IG Score Before Training']

In [112]:
df

           Gene  IG Score Before Training  IG Score After Training  Difference
0           AFP                  0.268941                 0.268941         0.0
1      CEACAM21                  0.268941                 0.268941         0.0
2       CEACAM4                  0.268941                 0.268941         0.0
3       CEACAM7                  0.268941                 0.268941         0.0
4       CEACAM5                  0.268941                 0.268941         0.0
..          ...                       ...                      ...         ...
263   KRTAP12-4                  0.268941                 0.268941         0.0
264   KRTAP12-3                  0.268941                 0.268941         0.0
265   KRTAP12-2                  0.268941                 0.268941         0.0
266   KRTAP12-1                  0.268941                 0.268941         0.0
267  KRTAP10-12                  0.268941                 0.268941         0.0

[268 rows x 4 columns]

In [127]:

# Sort the DataFrame by the Difference column in descending order
df = df.sort_values(by='IG Score After Training', ascending=False)

In [114]:
df['rank'] = df['Difference'].rank(ascending=False)

In [128]:
df.head(10)

          Gene  IG Score Before Training  IG Score After Training
13        MUC1                  0.268941                 0.273784
94      MAGED1                  0.268941                 0.273364
155      KRT18                  0.268941                 0.269840
190   KRTAP4-1                  0.268941                 0.268941
189   KRTAP4-2                  0.268941                 0.268941
188   KRTAP4-3                  0.268941                 0.268941
203     KRT33B                  0.268941                 0.268941
202     KRT33A                  0.268941                 0.268941
201  KRTAP17-1                  0.268941                 0.268941
145      KRT73                  0.268941                 0.268941

In [116]:
import os
# Write the sorted DataFrame to a CSV file
df.to_csv('./changes.csv', index=False)

torch.save(model.state_dict(), './final_model.pth')

In [117]:
df =  df[df['Difference'] != 0]
df

,Gene,IG Score Before Training,IG Score After Training,Difference,rank
13,MUC1,0.268941,0.273784,0.004843,1.0
94,MAGED1,0.268941,0.273364,0.004423,2.0
155,KRT18,0.268941,0.269840,0.000899,3.0
217,KRT17,0.268941,0.267564,-0.001377,257.0
141,KRT5,0.268941,0.266354,-0.002587,258.0
75,PMEL,0.268941,0.259548,-0.009393,259.0
97,MAGED2,0.268941,0.258832,-0.010109,260.0
116,KRTCAP2,0.268941,0.258829,-0.010112,261.0
24,EPCAM,0.268941,0.257976,-0.010965,262.0
22,MLANA,0.268941,0.257363,-0.011579,263.0
213,KRT19,0.268941,0.250689,-0.018252,264.0
20,SOX2,0.268941,0.243330,-0.025612,265.0
154,KRT8,0.268941,0.239850,-0.029091,266.0
212,KRT15,0.268941,0.239512,-0.029429,267.0
140,KRT6A,0.268941,0.238749,-0.030193,268.0

In [118]:
tumor_antigen = pd.read_csv('tumor_antigen.csv')

In [119]:
common_genes = pd.merge(df, tumor_antigen[['Gene']], on='Gene')

In [120]:
common_genes

,Gene,IG Score Before Training,IG Score After Training,Difference,rank
0,MUC1,0.268941,0.273784,0.004843,1.0
1,MAGED1,0.268941,0.273364,0.004423,2.0
2,KRT18,0.268941,0.269840,0.000899,3.0
3,KRT17,0.268941,0.267564,-0.001377,257.0
4,KRT5,0.268941,0.266354,-0.002587,258.0
5,PMEL,0.268941,0.259548,-0.009393,259.0
6,MAGED2,0.268941,0.258832,-0.010109,260.0
7,KRTCAP2,0.268941,0.258829,-0.010112,261.0
8,EPCAM,0.268941,0.257976,-0.010965,262.0
9,MLANA,0.268941,0.257363,-0.011579,263.0
10,KRT19,0.268941,0.250689,-0.018252,264.0
11,SOX2,0.268941,0.243330,-0.025612,265.0
12,KRT8,0.268941,0.239850,-0.029091,266.0
13,KRT15,0.268941,0.239512,-0.029429,267.0
14,KRT6A,0.268941,0.238749,-0.030193,268.0