In [1]:
import pandas as pd

In [16]:
results = pd.read_csv('validation/cripser/cytokine/science.abj4008_table_s2.csv')
results

,Gene,Screen_Version,CRISPRa_or_i,CD4_or_CD8,Cytokine,LFC,zscore,FDR,Hit,Hit_Type,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,A1BG,Primary,CRISPRa,CD8,IFNG,0.391920,1.598029,0.218667,False,NaN,NaN,NaN,NaN
1,A1BG,Primary,CRISPRa,CD4,IL2,0.026020,0.142965,0.853943,False,NaN,NaN,NaN,NaN
2,A1BG,Primary,CRISPRi,CD8,IFNG,-0.138240,0.806400,0.629077,False,NaN,NaN,NaN,NaN
3,A1BG,Primary,CRISPRi,CD4,IL2,-0.045950,0.326777,0.746672,False,NaN,NaN,NaN,NaN
4,A1BG,CD4_Supplement,CRISPRa,CD4,IFNG,0.349210,1.792897,0.252189,False,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
132523,ZZZ3,Primary,CRISPRi,CD8,IFNG,0.354510,-2.091032,0.244294,False,NaN,NaN,NaN,NaN
132524,ZZZ3,Primary,CRISPRi,CD4,IL2,0.028795,-0.123223,0.283681,False,NaN,NaN,NaN,NaN
132525,ZZZ3,CD4_Supplement,CRISPRa,CD4,IFNG,-0.458650,-2.310223,0.146867,False,NaN,NaN,NaN,NaN
132526,ZZZ3,CD4_Supplement,CRISPRa,CD4,IL2,0.104140,0.419935,0.916797,False,NaN,NaN,NaN,NaN
132527,ZZZ3,CD4_Supplement,CRISPRa,CD4,TNF,-0.145770,-0.491564,0.801047,False,NaN,NaN,NaN,NaN

In [17]:
results.drop(columns=['Unnamed: 10','Unnamed: 11','Unnamed: 12'], inplace=True)
results

,Gene,Screen_Version,CRISPRa_or_i,CD4_or_CD8,Cytokine,LFC,zscore,FDR,Hit,Hit_Type
0,A1BG,Primary,CRISPRa,CD8,IFNG,0.391920,1.598029,0.218667,False,NaN
1,A1BG,Primary,CRISPRa,CD4,IL2,0.026020,0.142965,0.853943,False,NaN
2,A1BG,Primary,CRISPRi,CD8,IFNG,-0.138240,0.806400,0.629077,False,NaN
3,A1BG,Primary,CRISPRi,CD4,IL2,-0.045950,0.326777,0.746672,False,NaN
4,A1BG,CD4_Supplement,CRISPRa,CD4,IFNG,0.349210,1.792897,0.252189,False,NaN
...,...,...,...,...,...,...,...,...,...,...
132523,ZZZ3,Primary,CRISPRi,CD8,IFNG,0.354510,-2.091032,0.244294,False,NaN
132524,ZZZ3,Primary,CRISPRi,CD4,IL2,0.028795,-0.123223,0.283681,False,NaN
132525,ZZZ3,CD4_Supplement,CRISPRa,CD4,IFNG,-0.458650,-2.310223,0.146867,False,NaN
132526,ZZZ3,CD4_Supplement,CRISPRa,CD4,IL2,0.104140,0.419935,0.916797,False,NaN
132527,ZZZ3,CD4_Supplement,CRISPRa,CD4,TNF,-0.145770,-0.491564,0.801047,False,NaN

In [18]:
results['Hit'].value_counts()

Hit
False    130246
True       2282
Name: count, dtype: int64

In [19]:
results = results[results['Hit']==True]
results

,Gene,Screen_Version,CRISPRa_or_i,CD4_or_CD8,Cytokine,LFC,zscore,FDR,Hit,Hit_Type
78,AADACL3,Primary,CRISPRa,CD4,IL2,0.82367,3.476327,0.000481,True,Positive Hit
199,AATF,Primary,CRISPRi,CD4,IL2,0.54996,-3.260886,0.000299,True,Negative Hit
223,ABCA1,CD4_Supplement,CRISPRa,CD4,TNF,0.66403,2.492527,0.008570,True,Positive Hit
309,ABCB10,Primary,CRISPRa,CD4,IL2,0.82566,3.484643,0.000101,True,Positive Hit
392,ABCC2,Primary,CRISPRa,CD8,IFNG,-0.53641,-1.973976,0.041465,True,Negative Hit
...,...,...,...,...,...,...,...,...,...,...
131264,ZNF701,Primary,CRISPRa,CD4,IL2,0.56371,2.389959,0.020885,True,Positive Hit
131492,ZNF740,CD4_Supplement,CRISPRa,CD4,IL2,-0.64152,-2.347148,0.025293,True,Negative Hit
132120,ZNHIT3,CD4_Supplement,CRISPRa,CD4,IL2,0.69609,2.616613,0.040560,True,Positive Hit
132423,ZSWIM6,Primary,CRISPRa,CD8,IFNG,-0.76361,-2.848190,0.022827,True,Negative Hit
132437,ZSWIM8,Primary,CRISPRa,CD8,IFNG,-0.82046,-3.066936,0.000081,True,Negative Hit

In [21]:
results.columns.to_list

<bound method IndexOpsMixin.tolist of Index(['Gene', 'Screen_Version', 'CRISPRa_or_i', 'CD4_or_CD8', 'Cytokine',
       'LFC', 'zscore', 'FDR', 'Hit', 'Hit_Type'],
      dtype='object')>

In [22]:
grouped = results.groupby('Gene')

In [23]:
filtered = grouped.filter(lambda x: x['Hit_Type'].nunique() == 1).drop_duplicates(subset='Gene', keep='first')

In [24]:
filtered

,Gene,Screen_Version,CRISPRa_or_i,CD4_or_CD8,Cytokine,LFC,zscore,FDR,Hit,Hit_Type
78,AADACL3,Primary,CRISPRa,CD4,IL2,0.82367,3.476327,0.000481,True,Positive Hit
199,AATF,Primary,CRISPRi,CD4,IL2,0.54996,-3.260886,0.000299,True,Negative Hit
223,ABCA1,CD4_Supplement,CRISPRa,CD4,TNF,0.66403,2.492527,0.008570,True,Positive Hit
309,ABCB10,Primary,CRISPRa,CD4,IL2,0.82566,3.484643,0.000101,True,Positive Hit
392,ABCC2,Primary,CRISPRa,CD8,IFNG,-0.53641,-1.973976,0.041465,True,Negative Hit
...,...,...,...,...,...,...,...,...,...,...
131264,ZNF701,Primary,CRISPRa,CD4,IL2,0.56371,2.389959,0.020885,True,Positive Hit
131492,ZNF740,CD4_Supplement,CRISPRa,CD4,IL2,-0.64152,-2.347148,0.025293,True,Negative Hit
132120,ZNHIT3,CD4_Supplement,CRISPRa,CD4,IL2,0.69609,2.616613,0.040560,True,Positive Hit
132423,ZSWIM6,Primary,CRISPRa,CD8,IFNG,-0.76361,-2.848190,0.022827,True,Negative Hit
132437,ZSWIM8,Primary,CRISPRa,CD8,IFNG,-0.82046,-3.066936,0.000081,True,Negative Hit

In [25]:
final_results = filtered[['Gene', 'Hit_Type']]

In [27]:
final_results['Gene'].nunique()

1443

In [28]:
final_results

           Gene      Hit_Type
78      AADACL3  Positive Hit
199        AATF  Negative Hit
223       ABCA1  Positive Hit
309      ABCB10  Positive Hit
392       ABCC2  Negative Hit
...         ...           ...
131264   ZNF701  Positive Hit
131492   ZNF740  Negative Hit
132120   ZNHIT3  Positive Hit
132423   ZSWIM6  Negative Hit
132437   ZSWIM8  Negative Hit

[1443 rows x 2 columns]

In [30]:
diff_gene = pd.read_csv('validation/diff_gene/all_data_diff_gene_markers_top5000_filtered.csv')
diff_gene

,gene,logfoldchange,pvals,adjusted_pvals,average_count,Unnamed: 5
0,MSLN,-0.996481,3.220000e-26,2.010000e-23,0.082340,0.996481
1,SLC34A2,-0.972979,4.710000e-29,3.410000e-26,0.097124,0.972979
2,CARTPT,-0.903900,1.140000e-24,6.270000e-22,0.107048,0.903900
3,CD24,0.889778,7.230000e-142,1.310000e-137,1.541697,0.889778
4,MX1,0.790000,2.140000e-48,3.230000e-45,0.267711,0.790000
...,...,...,...,...,...,...
4921,CTSA,-0.000085,9.985001e-01,1.000000e+00,0.406757,0.000085
4922,USP10,0.000079,9.992639e-01,1.000000e+00,0.092019,0.000079
4923,CYTH2,-0.000076,9.990819e-01,1.000000e+00,0.163470,0.000076
4924,YIPF5,-0.000035,9.996513e-01,1.000000e+00,0.107927,0.000035
4925,RIN2,-0.000016,9.997787e-01,1.000000e+00,0.213874,0.000016

In [31]:
final_results = final_results.merge(diff_gene, left_on='Gene', right_on='gene', how='left')

In [32]:
final_results

,Gene,Hit_Type,gene,logfoldchange,pvals,adjusted_pvals,average_count,Unnamed: 5
0,AADACL3,Positive Hit,NaN,NaN,NaN,NaN,NaN,NaN
1,AATF,Negative Hit,AATF,-0.100273,0.170988,0.491859,0.129041,0.100273
2,ABCA1,Positive Hit,ABCA1,0.080201,0.202474,0.535578,0.183519,0.080201
3,ABCB10,Positive Hit,NaN,NaN,NaN,NaN,NaN,NaN
4,ABCC2,Negative Hit,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
1438,ZNF701,Positive Hit,NaN,NaN,NaN,NaN,NaN,NaN
1439,ZNF740,Negative Hit,NaN,NaN,NaN,NaN,NaN,NaN
1440,ZNHIT3,Positive Hit,NaN,NaN,NaN,NaN,NaN,NaN
1441,ZSWIM6,Negative Hit,NaN,NaN,NaN,NaN,NaN,NaN
1442,ZSWIM8,Negative Hit,ZSWIM8,-0.011690,0.870967,0.961509,0.136125,0.011690

In [33]:
final_results.dropna(inplace=True)
final_results

,Gene,Hit_Type,gene,logfoldchange,pvals,adjusted_pvals,average_count,Unnamed: 5
1,AATF,Negative Hit,AATF,-0.100273,1.709879e-01,0.491859,0.129041,0.100273
2,ABCA1,Positive Hit,ABCA1,0.080201,2.024743e-01,0.535578,0.183519,0.080201
8,ACAP2,Positive Hit,ACAP2,-0.091677,1.898756e-01,0.518873,0.143911,0.091677
12,ACTL6A,Negative Hit,ACTL6A,0.010725,9.065213e-01,0.974658,0.080664,0.010725
13,ADAM19,Positive Hit,ADAM19,-0.337112,4.020000e-07,0.000028,0.166212,0.337112
...,...,...,...,...,...,...,...,...
1427,ZMYND11,Positive Hit,ZMYND11,0.115706,1.782114e-01,0.502686,0.093596,0.115706
1428,ZNF106,Negative Hit,ZNF106,0.169906,3.052281e-02,0.200074,0.111217,0.169906
1429,ZNF148,Negative Hit,ZNF148,0.089450,2.806560e-01,0.620833,0.100230,0.089450
1436,ZNF580,Negative Hit,ZNF580,0.071897,4.208276e-01,0.726852,0.083169,0.071897
1442,ZSWIM8,Negative Hit,ZSWIM8,-0.011690,8.709674e-01,0.961509,0.136125,0.011690

In [35]:
final_results['Hit_Type'] = final_results['Hit_Type'].apply(lambda x: 1 if x == 'Negative Hit' else -1)

In [36]:
final_results

,Gene,Hit_Type,gene,logfoldchange,pvals,adjusted_pvals,average_count,Unnamed: 5
1,AATF,1,AATF,-0.100273,1.709879e-01,0.491859,0.129041,0.100273
2,ABCA1,-1,ABCA1,0.080201,2.024743e-01,0.535578,0.183519,0.080201
8,ACAP2,-1,ACAP2,-0.091677,1.898756e-01,0.518873,0.143911,0.091677
12,ACTL6A,1,ACTL6A,0.010725,9.065213e-01,0.974658,0.080664,0.010725
13,ADAM19,-1,ADAM19,-0.337112,4.020000e-07,0.000028,0.166212,0.337112
...,...,...,...,...,...,...,...,...
1427,ZMYND11,-1,ZMYND11,0.115706,1.782114e-01,0.502686,0.093596,0.115706
1428,ZNF106,1,ZNF106,0.169906,3.052281e-02,0.200074,0.111217,0.169906
1429,ZNF148,1,ZNF148,0.089450,2.806560e-01,0.620833,0.100230,0.089450
1436,ZNF580,1,ZNF580,0.071897,4.208276e-01,0.726852,0.083169,0.071897
1442,ZSWIM8,1,ZSWIM8,-0.011690,8.709674e-01,0.961509,0.136125,0.011690

In [38]:
final_results['cosistancy'] = final_results['Hit_Type'] * final_results['logfoldchange']

In [39]:
final_results

,Gene,Hit_Type,gene,logfoldchange,pvals,adjusted_pvals,average_count,Unnamed: 5,cosistancy
1,AATF,1,AATF,-0.100273,1.709879e-01,0.491859,0.129041,0.100273,-0.100273
2,ABCA1,-1,ABCA1,0.080201,2.024743e-01,0.535578,0.183519,0.080201,-0.080201
8,ACAP2,-1,ACAP2,-0.091677,1.898756e-01,0.518873,0.143911,0.091677,0.091677
12,ACTL6A,1,ACTL6A,0.010725,9.065213e-01,0.974658,0.080664,0.010725,0.010725
13,ADAM19,-1,ADAM19,-0.337112,4.020000e-07,0.000028,0.166212,0.337112,0.337112
...,...,...,...,...,...,...,...,...,...
1427,ZMYND11,-1,ZMYND11,0.115706,1.782114e-01,0.502686,0.093596,0.115706,-0.115706
1428,ZNF106,1,ZNF106,0.169906,3.052281e-02,0.200074,0.111217,0.169906,0.169906
1429,ZNF148,1,ZNF148,0.089450,2.806560e-01,0.620833,0.100230,0.089450,0.089450
1436,ZNF580,1,ZNF580,0.071897,4.208276e-01,0.726852,0.083169,0.071897,0.071897
1442,ZSWIM8,1,ZSWIM8,-0.011690,8.709674e-01,0.961509,0.136125,0.011690,-0.011690

In [40]:
final_results['cosistancy'] = final_results['cosistancy'].apply(lambda x: True if x > 0 else False)

In [41]:
final_results

,Gene,Hit_Type,gene,logfoldchange,pvals,adjusted_pvals,average_count,Unnamed: 5,cosistancy
1,AATF,1,AATF,-0.100273,1.709879e-01,0.491859,0.129041,0.100273,False
2,ABCA1,-1,ABCA1,0.080201,2.024743e-01,0.535578,0.183519,0.080201,False
8,ACAP2,-1,ACAP2,-0.091677,1.898756e-01,0.518873,0.143911,0.091677,True
12,ACTL6A,1,ACTL6A,0.010725,9.065213e-01,0.974658,0.080664,0.010725,True
13,ADAM19,-1,ADAM19,-0.337112,4.020000e-07,0.000028,0.166212,0.337112,True
...,...,...,...,...,...,...,...,...,...
1427,ZMYND11,-1,ZMYND11,0.115706,1.782114e-01,0.502686,0.093596,0.115706,False
1428,ZNF106,1,ZNF106,0.169906,3.052281e-02,0.200074,0.111217,0.169906,True
1429,ZNF148,1,ZNF148,0.089450,2.806560e-01,0.620833,0.100230,0.089450,True
1436,ZNF580,1,ZNF580,0.071897,4.208276e-01,0.726852,0.083169,0.071897,True
1442,ZSWIM8,1,ZSWIM8,-0.011690,8.709674e-01,0.961509,0.136125,0.011690,False

In [43]:
final_results['cosistancy'].value_counts()

cosistancy
True     270
False    262
Name: count, dtype: int64

In [44]:
final_results.to_csv('validation/cripser/cytokine/cripser_cytokine_final_results.csv', index=False)