In [1]:
import pandas as pd

In [7]:
df = pd.read_csv('validation/cripser/key_regulators/mageck.csv')
df

,id,num,neg|score,neg|p-value,neg|fdr,neg|rank,neg|goodsgrna,neg|lfc,pos|score,pos|p-value,pos|fdr,pos|rank,pos|goodsgrna,pos|lfc
0,LCP2,4,3.050000e-10,2.560000e-07,0.00019,1,4,-1.32880,1.000000e+00,1.000000e+00,1.000000,19113,0,-1.32880
1,RHOH,4,9.060000e-10,2.560000e-07,0.00019,2,4,-0.83253,1.000000e+00,1.000000e+00,1.000000,19114,0,-0.83253
2,CD247,4,1.140000e-09,2.560000e-07,0.00019,3,4,-0.95712,1.000000e+00,1.000000e+00,1.000000,19110,0,-0.95712
3,VAV1,4,1.440000e-09,2.560000e-07,0.00019,4,3,-1.33260,1.245400e-01,2.939700e-01,1.000000,4149,1,-1.33260
4,MYC,4,7.730000e-09,2.560000e-07,0.00019,5,3,-0.88604,9.836600e-01,9.944100e-01,1.000000,18641,0,-0.88604
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19109,CUL3,4,9.999900e-01,9.999800e-01,1.00000,19110,0,0.33645,8.490000e-06,1.551800e-04,0.251238,10,4,0.33645
19110,FIBP,4,1.000000e+00,9.999900e-01,1.00000,19111,0,0.59447,9.200000e-07,1.050000e-05,0.033828,6,4,0.59447
19111,CD8A,4,1.000000e+00,1.000000e+00,1.00000,19112,0,0.56972,1.150000e-07,2.300000e-06,0.011139,4,4,0.56972
19112,DGKZ,4,1.000000e+00,1.000000e+00,1.00000,19113,0,0.52445,2.640000e-08,1.280000e-06,0.008251,2,4,0.52445
19113,MEF2D,4,1.000000e+00,1.000000e+00,1.00000,19114,0,0.40273,1.700000e-08,7.670000e-07,0.008251,1,4,0.40273

In [8]:
df = df[(df['neg|p-value'] < 0.05) | (df['pos|p-value'] < 0.05)]
df = df[(df['neg|fdr'] < 0.05) | (df['pos|fdr'] < 0.05)]
df

,id,num,neg|score,neg|p-value,neg|fdr,neg|rank,neg|goodsgrna,neg|lfc,pos|score,pos|p-value,pos|fdr,pos|rank,pos|goodsgrna,pos|lfc
0,LCP2,4,3.050000e-10,2.560000e-07,0.00019,1,4,-1.32880,1.000000e+00,1.000000e+00,1.000000,19113,0,-1.32880
1,RHOH,4,9.060000e-10,2.560000e-07,0.00019,2,4,-0.83253,1.000000e+00,1.000000e+00,1.000000,19114,0,-0.83253
2,CD247,4,1.140000e-09,2.560000e-07,0.00019,3,4,-0.95712,1.000000e+00,1.000000e+00,1.000000,19110,0,-0.95712
3,VAV1,4,1.440000e-09,2.560000e-07,0.00019,4,3,-1.33260,1.245400e-01,2.939700e-01,1.000000,4149,1,-1.33260
4,MYC,4,7.730000e-09,2.560000e-07,0.00019,5,3,-0.88604,9.836600e-01,9.944100e-01,1.000000,18641,0,-0.88604
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19095,CBLB,4,9.997300e-01,9.993200e-01,1.00000,19096,0,1.11530,4.320000e-08,1.280000e-06,0.008251,3,4,1.11530
19110,FIBP,4,1.000000e+00,9.999900e-01,1.00000,19111,0,0.59447,9.200000e-07,1.050000e-05,0.033828,6,4,0.59447
19111,CD8A,4,1.000000e+00,1.000000e+00,1.00000,19112,0,0.56972,1.150000e-07,2.300000e-06,0.011139,4,4,0.56972
19112,DGKZ,4,1.000000e+00,1.000000e+00,1.00000,19113,0,0.52445,2.640000e-08,1.280000e-06,0.008251,2,4,0.52445
19113,MEF2D,4,1.000000e+00,1.000000e+00,1.00000,19114,0,0.40273,1.700000e-08,7.670000e-07,0.008251,1,4,0.40273

In [9]:
diff_gene = pd.read_csv('validation/diff_gene/all_data_diff_gene_markers_top5000_filtered.csv')
diff_gene

,gene,logfoldchange,pvals,adjusted_pvals,average_count,Unnamed: 5
0,MSLN,-0.996481,3.220000e-26,2.010000e-23,0.082340,0.996481
1,SLC34A2,-0.972979,4.710000e-29,3.410000e-26,0.097124,0.972979
2,CARTPT,-0.903900,1.140000e-24,6.270000e-22,0.107048,0.903900
3,CD24,0.889778,7.230000e-142,1.310000e-137,1.541697,0.889778
4,MX1,0.790000,2.140000e-48,3.230000e-45,0.267711,0.790000
...,...,...,...,...,...,...
4921,CTSA,-0.000085,9.985001e-01,1.000000e+00,0.406757,0.000085
4922,USP10,0.000079,9.992639e-01,1.000000e+00,0.092019,0.000079
4923,CYTH2,-0.000076,9.990819e-01,1.000000e+00,0.163470,0.000076
4924,YIPF5,-0.000035,9.996513e-01,1.000000e+00,0.107927,0.000035
4925,RIN2,-0.000016,9.997787e-01,1.000000e+00,0.213874,0.000016

In [10]:
df = df.merge(diff_gene, left_on='id', right_on='gene', how='left')
df

,id,num,neg|score,neg|p-value,neg|fdr,neg|rank,neg|goodsgrna,neg|lfc,pos|score,pos|p-value,pos|fdr,pos|rank,pos|goodsgrna,pos|lfc,gene,logfoldchange,pvals,adjusted_pvals,average_count,Unnamed: 5
0,LCP2,4,3.050000e-10,2.560000e-07,0.00019,1,4,-1.32880,1.000000e+00,1.000000e+00,1.000000,19113,0,-1.32880,LCP2,-0.080754,0.104898,0.394567,0.320332,0.080754
1,RHOH,4,9.060000e-10,2.560000e-07,0.00019,2,4,-0.83253,1.000000e+00,1.000000e+00,1.000000,19114,0,-0.83253,RHOH,0.035988,0.705460,0.894611,0.073894,0.035988
2,CD247,4,1.140000e-09,2.560000e-07,0.00019,3,4,-0.95712,1.000000e+00,1.000000e+00,1.000000,19110,0,-0.95712,NaN,NaN,NaN,NaN,NaN,NaN
3,VAV1,4,1.440000e-09,2.560000e-07,0.00019,4,3,-1.33260,1.245400e-01,2.939700e-01,1.000000,4149,1,-1.33260,VAV1,-0.170044,0.016820,0.137085,0.139131,0.170044
4,MYC,4,7.730000e-09,2.560000e-07,0.00019,5,3,-0.88604,9.836600e-01,9.944100e-01,1.000000,18641,0,-0.88604,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,CBLB,4,9.997300e-01,9.993200e-01,1.00000,19096,0,1.11530,4.320000e-08,1.280000e-06,0.008251,3,4,1.11530,CBLB,-0.092372,0.219422,0.554625,0.126039,0.092372
193,FIBP,4,1.000000e+00,9.999900e-01,1.00000,19111,0,0.59447,9.200000e-07,1.050000e-05,0.033828,6,4,0.59447,FIBP,-0.047986,0.576939,0.829078,0.091207,0.047986
194,CD8A,4,1.000000e+00,1.000000e+00,1.00000,19112,0,0.56972,1.150000e-07,2.300000e-06,0.011139,4,4,0.56972,CD8A,-0.112148,0.091222,0.364925,0.165872,0.112148
195,DGKZ,4,1.000000e+00,1.000000e+00,1.00000,19113,0,0.52445,2.640000e-08,1.280000e-06,0.008251,2,4,0.52445,DGKZ,-0.212056,0.015061,0.126926,0.090135,0.212056
196,MEF2D,4,1.000000e+00,1.000000e+00,1.00000,19114,0,0.40273,1.700000e-08,7.670000e-07,0.008251,1,4,0.40273,MEF2D,-0.069936,0.259875,0.601541,0.186461,0.069936

In [12]:
df.dropna(subset=['gene'], inplace=True)
df

,id,num,neg|score,neg|p-value,neg|fdr,neg|rank,neg|goodsgrna,neg|lfc,pos|score,pos|p-value,pos|fdr,pos|rank,pos|goodsgrna,pos|lfc,gene,logfoldchange,pvals,adjusted_pvals,average_count,Unnamed: 5
0,LCP2,4,3.050000e-10,2.560000e-07,0.00019,1,4,-1.32880,1.000000e+00,1.000000e+00,1.000000,19113,0,-1.32880,LCP2,-0.080754,1.048979e-01,3.945672e-01,0.320332,0.080754
1,RHOH,4,9.060000e-10,2.560000e-07,0.00019,2,4,-0.83253,1.000000e+00,1.000000e+00,1.000000,19114,0,-0.83253,RHOH,0.035988,7.054598e-01,8.946109e-01,0.073894,0.035988
3,VAV1,4,1.440000e-09,2.560000e-07,0.00019,4,3,-1.33260,1.245400e-01,2.939700e-01,1.000000,4149,1,-1.33260,VAV1,-0.170044,1.682019e-02,1.370849e-01,0.139131,0.170044
5,CD3D,4,1.100000e-08,2.560000e-07,0.00019,6,4,-1.32170,1.000000e+00,1.000000e+00,1.000000,19111,0,-1.32170,CD3D,-0.407979,2.220000e-11,3.460000e-09,0.203933,0.407979
6,NELFCD,4,1.720000e-08,2.560000e-07,0.00019,7,4,-0.55683,1.000000e+00,1.000000e+00,1.000000,19112,0,-0.55683,NELFCD,-0.149406,7.275078e-02,3.330881e-01,0.098947,0.149406
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,CBLB,4,9.997300e-01,9.993200e-01,1.00000,19096,0,1.11530,4.320000e-08,1.280000e-06,0.008251,3,4,1.11530,CBLB,-0.092372,2.194224e-01,5.546249e-01,0.126039,0.092372
193,FIBP,4,1.000000e+00,9.999900e-01,1.00000,19111,0,0.59447,9.200000e-07,1.050000e-05,0.033828,6,4,0.59447,FIBP,-0.047986,5.769393e-01,8.290781e-01,0.091207,0.047986
194,CD8A,4,1.000000e+00,1.000000e+00,1.00000,19112,0,0.56972,1.150000e-07,2.300000e-06,0.011139,4,4,0.56972,CD8A,-0.112148,9.122226e-02,3.649254e-01,0.165872,0.112148
195,DGKZ,4,1.000000e+00,1.000000e+00,1.00000,19113,0,0.52445,2.640000e-08,1.280000e-06,0.008251,2,4,0.52445,DGKZ,-0.212056,1.506125e-02,1.269258e-01,0.090135,0.212056
196,MEF2D,4,1.000000e+00,1.000000e+00,1.00000,19114,0,0.40273,1.700000e-08,7.670000e-07,0.008251,1,4,0.40273,MEF2D,-0.069936,2.598749e-01,6.015406e-01,0.186461,0.069936

In [14]:
df['consistancy'] = df.apply(lambda x: True if x['neg|lfc'] * x['logfoldchange'] > 0 else False, axis=1)

In [15]:
df

,id,num,neg|score,neg|p-value,neg|fdr,neg|rank,neg|goodsgrna,neg|lfc,pos|score,pos|p-value,...,pos|rank,pos|goodsgrna,pos|lfc,gene,logfoldchange,pvals,adjusted_pvals,average_count,Unnamed: 5,consistancy
0,LCP2,4,3.050000e-10,2.560000e-07,0.00019,1,4,-1.32880,1.000000e+00,1.000000e+00,...,19113,0,-1.32880,LCP2,-0.080754,1.048979e-01,3.945672e-01,0.320332,0.080754,True
1,RHOH,4,9.060000e-10,2.560000e-07,0.00019,2,4,-0.83253,1.000000e+00,1.000000e+00,...,19114,0,-0.83253,RHOH,0.035988,7.054598e-01,8.946109e-01,0.073894,0.035988,False
3,VAV1,4,1.440000e-09,2.560000e-07,0.00019,4,3,-1.33260,1.245400e-01,2.939700e-01,...,4149,1,-1.33260,VAV1,-0.170044,1.682019e-02,1.370849e-01,0.139131,0.170044,True
5,CD3D,4,1.100000e-08,2.560000e-07,0.00019,6,4,-1.32170,1.000000e+00,1.000000e+00,...,19111,0,-1.32170,CD3D,-0.407979,2.220000e-11,3.460000e-09,0.203933,0.407979,True
6,NELFCD,4,1.720000e-08,2.560000e-07,0.00019,7,4,-0.55683,1.000000e+00,1.000000e+00,...,19112,0,-0.55683,NELFCD,-0.149406,7.275078e-02,3.330881e-01,0.098947,0.149406,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,CBLB,4,9.997300e-01,9.993200e-01,1.00000,19096,0,1.11530,4.320000e-08,1.280000e-06,...,3,4,1.11530,CBLB,-0.092372,2.194224e-01,5.546249e-01,0.126039,0.092372,False
193,FIBP,4,1.000000e+00,9.999900e-01,1.00000,19111,0,0.59447,9.200000e-07,1.050000e-05,...,6,4,0.59447,FIBP,-0.047986,5.769393e-01,8.290781e-01,0.091207,0.047986,False
194,CD8A,4,1.000000e+00,1.000000e+00,1.00000,19112,0,0.56972,1.150000e-07,2.300000e-06,...,4,4,0.56972,CD8A,-0.112148,9.122226e-02,3.649254e-01,0.165872,0.112148,False
195,DGKZ,4,1.000000e+00,1.000000e+00,1.00000,19113,0,0.52445,2.640000e-08,1.280000e-06,...,2,4,0.52445,DGKZ,-0.212056,1.506125e-02,1.269258e-01,0.090135,0.212056,False
196,MEF2D,4,1.000000e+00,1.000000e+00,1.00000,19114,0,0.40273,1.700000e-08,7.670000e-07,...,1,4,0.40273,MEF2D,-0.069936,2.598749e-01,6.015406e-01,0.186461,0.069936,False

In [16]:
df['consistancy'].value_counts()

consistancy
True     63
False    37
Name: count, dtype: int64

In [17]:
df.to_csv('validation/cripser/key_regulators/final_results_key_regulators.csv', index=False)

In [ ]:
https://www.cell.com/cell/fulltext/S0092-8674(18)31333-3